//! Writes `app/src/lib/protocol.gen.ts`. Run it with
//! `cargo test -p botloft-core export_bindings`; CI fails if the committed
//! file differs from what this produces.

use std::fmt::Write as _;
use std::path::Path;

use ts_rs::{Config, TS};

use super::*;
use crate::avatar::PALETTE;
use crate::ids::{
    ApprovalId, AttachmentId, BotId, ChatItemId, CrewAccessId, CrewId, DeliveryId, DesktopGrantId,
    McpServerId, MessageId, QuestionId, RoutineId, RoutineRunId, RuleId, TaskId,
};

#[path = "export_backup.rs"]
mod backup;
#[path = "export_browser.rs"]
mod browser;
#[path = "export_catalog.rs"]
mod catalog;
#[path = "export_cloud.rs"]
mod cloud;
#[path = "export_crew_access.rs"]
mod crew_access;
#[path = "export_desktop.rs"]
mod desktop;
#[path = "export_mcp.rs"]
mod mcp;
#[path = "export_mobile.rs"]
mod mobile;
#[path = "export_questions.rs"]
mod questions;
#[path = "export_reactions.rs"]
mod reactions;
#[path = "export_routines.rs"]
mod routines;
#[path = "export_rules.rs"]
mod rules;
#[path = "export_search.rs"]
mod search;
#[path = "export_session.rs"]
mod session;
#[path = "export_usage.rs"]
mod usage;
use crate::validate;

const HEADER: &str = "\
// Generated by `cargo test -p botloft-core export_bindings`. Do not edit by hand.
// Source: crates/botloft-core/src/protocol.
";

struct Out {
    cfg: Config,
    text: String,
}

impl Out {
    fn decl<T: TS>(&mut self) {
        if let Some(docs) = T::docs() {
            self.text.push_str(&docs);
        }
        let _ = writeln!(self.text, "export {}\n", T::decl(&self.cfg));
    }

    fn method(&mut self, name: &str, params: &str, result: &str) {
        let _ = writeln!(
            self.text,
            "  \"{name}\": {{ params: {params}; result: {result} }};"
        );
    }

    fn name<T: TS>(&self) -> String {
        T::name(&self.cfg)
    }
}

#[test]
fn export_bindings() {
    let mut out = Out {
        cfg: Config::new().with_large_int("number"),
        text: String::from(HEADER),
    };
    let _ = writeln!(
        out.text,
        "\nexport const PROTOCOL_VERSION = {PROTOCOL_VERSION};\n"
    );
    out.text
        .push_str("/** Avatar colors the daemon assigns in order (spec 15.3). */\n");
    let palette: Vec<String> = PALETTE.iter().map(|color| format!("\"{color}\"")).collect();
    let _ = writeln!(
        out.text,
        "export const AVATAR_PALETTE = [{}] as const;\n",
        palette.join(", ")
    );
    out.text.push_str(
        "/** Longest values the daemon accepts, in characters (files, for attachments). */\n",
    );
    out.text.push_str("export const FIELD_LIMITS = {\n");
    for (name, max) in [
        ("name", validate::NAME_MAX_CHARS),
        ("role", validate::ROLE_MAX_CHARS),
        ("instructions", validate::INSTRUCTIONS_MAX_CHARS),
        ("message", validate::MESSAGE_MAX_CHARS),
        ("attachments", validate::ATTACHMENTS_MAX),
    ] {
        let _ = writeln!(out.text, "  {name}: {max},");
    }
    out.text.push_str("} as const;\n\n");

    out.decl::<CrewId>();
    out.decl::<BotId>();
    out.decl::<MessageId>();
    out.decl::<DeliveryId>();
    out.decl::<TaskId>();
    out.decl::<ChatItemId>();
    out.decl::<ApprovalId>();
    out.decl::<AttachmentId>();
    out.decl::<RoutineId>();
    out.decl::<RoutineRunId>();
    out.decl::<RuleId>();
    out.decl::<QuestionId>();
    out.decl::<DesktopGrantId>();
    out.decl::<McpServerId>();
    out.decl::<CrewAccessId>();
    out.decl::<Crew>();
    out.decl::<BotState>();
    out.decl::<PermissionMode>();
    out.decl::<AgentKind>();
    out.decl::<BotModel>();
    out.decl::<ActivityKind>();
    out.decl::<Activity>();
    session::decls(&mut out);
    out.decl::<Bot>();
    out.decl::<ClientInfo>();
    out.decl::<HelloParams>();
    out.decl::<LocaleParams>();
    out.decl::<HelloResult>();
    out.decl::<DeliveryBacklog>();
    out.decl::<UsageWindow>();
    out.decl::<AccountUsage>();
    out.decl::<ClaudeAccount>();
    out.decl::<OwnerAccount>();
    out.decl::<SystemStatus>();
    out.decl::<CrewsCreateParams>();
    out.decl::<CrewsRenameParams>();
    out.decl::<CrewsSetColorParams>();
    out.decl::<CrewsSetPausedParams>();
    out.decl::<CrewsSetWorkFolderParams>();
    out.decl::<NewLead>();
    out.decl::<CrewsSetLeadParams>();
    out.decl::<CrewIdParams>();
    out.decl::<BotsListParams>();
    out.decl::<BotsCreateParams>();
    out.decl::<BotsUpdateParams>();
    out.decl::<BotsSetPausedParams>();
    out.decl::<BotsSetPermissionModeParams>();
    out.decl::<BotsSetModelParams>();
    out.decl::<BotIdParams>();
    out.decl::<BotsRestartParams>();
    out.decl::<BotStateChanged>();
    out.decl::<BotDeleted>();
    out.decl::<CrewDeleted>();
    out.decl::<Archive>();
    out.decl::<BotsDeleteParams>();
    out.decl::<CrewsDeleteParams>();
    out.decl::<FolderRecycled>();
    out.decl::<SenderKind>();
    out.decl::<MessageKind>();
    out.decl::<DeliveryState>();
    out.decl::<TaskStatus>();
    out.decl::<Attachment>();
    out.decl::<AttachmentUpload>();
    out.decl::<AttachmentIdParams>();
    out.decl::<AttachmentData>();
    out.decl::<BotFile>();
    out.decl::<FilesListParams>();
    out.decl::<FilesReadParams>();
    out.decl::<FileData>();
    out.decl::<Message>();
    out.decl::<MessageReply>();
    out.decl::<Delivery>();
    out.decl::<Task>();
    out.decl::<MessagesSendParams>();
    out.decl::<MessagesListParams>();
    out.decl::<DeliveriesListParams>();
    out.decl::<DeliveryIdParams>();
    out.decl::<TasksListParams>();
    out.decl::<ToolStatus>();
    out.decl::<ApprovalStatus>();
    out.decl::<NoticeLevel>();
    out.decl::<NoticeCode>();
    out.decl::<InboundItem>();
    out.decl::<ReplyItem>();
    out.decl::<ToolItem>();
    rules::decls(&mut out);
    desktop::decls(&mut out);
    mcp::decls(&mut out);
    crew_access::decls(&mut out);
    catalog::decls(&mut out);
    backup::decls(&mut out);
    cloud::decls(&mut out);
    mobile::decls(&mut out);
    out.decl::<ApprovalItem>();
    usage::decls(&mut out);
    questions::decls(&mut out);
    reactions::decls(&mut out);
    out.decl::<TurnItem>();
    out.decl::<NoticeItem>();
    out.decl::<ChatBody>();
    out.decl::<ChatItem>();
    out.decl::<ChatItemChanged>();
    search::decls(&mut out);
    out.decl::<Approval>();
    out.decl::<ChatDelta>();
    out.decl::<ChatHistoryParams>();
    out.decl::<ApprovalsAnswerParams>();
    out.decl::<Settings>();
    out.decl::<SettingsUpdateParams>();
    routines::decls(&mut out);
    browser::decls(&mut out);

    let crew = out.name::<Crew>();
    let bot = out.name::<Bot>();
    let crews = out.name::<Vec<Crew>>();
    let bots = out.name::<Vec<Bot>>();

    out.text
        .push_str("/** Params and result of every request method. */\n");
    out.text.push_str("export interface RpcMethods {\n");
    out.method(
        method::SESSION_HELLO,
        &out.name::<HelloParams>(),
        &out.name::<HelloResult>(),
    );
    out.method(
        method::SESSION_SET_LOCALE,
        &out.name::<LocaleParams>(),
        "null",
    );
    out.method(
        method::SYSTEM_STATUS,
        "undefined",
        &out.name::<SystemStatus>(),
    );
    out.method(
        method::SYSTEM_REFRESH,
        "undefined",
        &out.name::<SystemStatus>(),
    );
    out.method(method::SETTINGS_GET, "undefined", &out.name::<Settings>());
    out.method(
        method::SETTINGS_UPDATE,
        &out.name::<SettingsUpdateParams>(),
        &out.name::<Settings>(),
    );
    out.method(method::CREWS_LIST, "undefined", &crews);
    out.method(
        method::CREWS_CREATE,
        &out.name::<CrewsCreateParams>(),
        &crew,
    );
    out.method(
        method::CREWS_RENAME,
        &out.name::<CrewsRenameParams>(),
        &crew,
    );
    out.method(
        method::CREWS_SET_COLOR,
        &out.name::<CrewsSetColorParams>(),
        &crew,
    );
    out.method(
        method::CREWS_SET_PAUSED,
        &out.name::<CrewsSetPausedParams>(),
        &crew,
    );
    out.method(
        method::CREWS_SET_WORK_FOLDER,
        &out.name::<CrewsSetWorkFolderParams>(),
        &crew,
    );
    out.method(
        method::CREWS_SET_LEAD,
        &out.name::<CrewsSetLeadParams>(),
        &crew,
    );
    out.method(method::CREWS_ARCHIVE, &out.name::<CrewIdParams>(), &crew);
    let crew_deleted = out.name::<CrewDeleted>();
    let bot_deleted = out.name::<BotDeleted>();
    out.method(
        method::CREWS_DELETE,
        &out.name::<CrewsDeleteParams>(),
        &crew_deleted,
    );
    out.method(method::ARCHIVE_LIST, "undefined", &out.name::<Archive>());
    out.method(method::BOTS_LIST, &out.name::<BotsListParams>(), &bots);
    out.method(method::BOTS_CREATE, &out.name::<BotsCreateParams>(), &bot);
    out.method(method::BOTS_UPDATE, &out.name::<BotsUpdateParams>(), &bot);
    out.method(
        method::BOTS_SET_PAUSED,
        &out.name::<BotsSetPausedParams>(),
        &bot,
    );
    out.method(
        method::BOTS_SET_PERMISSION_MODE,
        &out.name::<BotsSetPermissionModeParams>(),
        &bot,
    );
    out.method(
        method::BOTS_SET_MODEL,
        &out.name::<BotsSetModelParams>(),
        &bot,
    );
    out.method(method::BOTS_ARCHIVE, &out.name::<BotIdParams>(), &bot);
    out.method(
        method::BOTS_DELETE,
        &out.name::<BotsDeleteParams>(),
        &bot_deleted,
    );
    out.method(method::BOTS_RESTART, &out.name::<BotsRestartParams>(), &bot);
    out.method(
        method::CHAT_HISTORY,
        &out.name::<ChatHistoryParams>(),
        &out.name::<Vec<ChatItem>>(),
    );
    out.method(method::CHAT_READ, &out.name::<BotIdParams>(), "null");
    out.method(
        method::APPROVALS_ANSWER,
        &out.name::<ApprovalsAnswerParams>(),
        &out.name::<Approval>(),
    );
    let message = out.name::<Message>();
    let delivery = out.name::<Delivery>();
    out.method(
        method::MESSAGES_SEND,
        &out.name::<MessagesSendParams>(),
        &message,
    );
    out.method(
        method::MESSAGES_LIST,
        &out.name::<MessagesListParams>(),
        &out.name::<Vec<Message>>(),
    );
    out.method(
        method::ATTACHMENTS_READ,
        &out.name::<AttachmentIdParams>(),
        &out.name::<AttachmentData>(),
    );
    out.method(
        method::FILES_LIST,
        &out.name::<FilesListParams>(),
        &out.name::<Vec<BotFile>>(),
    );
    out.method(
        method::FILES_READ,
        &out.name::<FilesReadParams>(),
        &out.name::<FileData>(),
    );
    out.method(
        method::DELIVERIES_LIST,
        &out.name::<DeliveriesListParams>(),
        &out.name::<Vec<Delivery>>(),
    );
    out.method(
        method::DELIVERIES_RETRY,
        &out.name::<DeliveryIdParams>(),
        &delivery,
    );
    out.method(
        method::TASKS_LIST,
        &out.name::<TasksListParams>(),
        &out.name::<Vec<Task>>(),
    );
    session::methods(&mut out);
    usage::methods(&mut out);
    rules::methods(&mut out);
    desktop::methods(&mut out);
    mcp::methods(&mut out);
    crew_access::methods(&mut out);
    catalog::methods(&mut out);
    backup::methods(&mut out);
    cloud::methods(&mut out);
    mobile::methods(&mut out);
    routines::methods(&mut out);
    questions::methods(&mut out);
    reactions::methods(&mut out);
    search::methods(&mut out);
    browser::methods(&mut out);
    out.text.push_str("}\n\n");

    out.text
        .push_str("/** Params of every server notification. */\n");
    out.text.push_str("export interface RpcNotifications {\n");
    let _ = writeln!(out.text, "  \"{}\": {crew};", notification::CREW_CHANGED);
    let _ = writeln!(out.text, "  \"{}\": {bot};", notification::BOT_CHANGED);
    let _ = writeln!(
        out.text,
        "  \"{}\": {crew_deleted};",
        notification::CREW_DELETED
    );
    let _ = writeln!(
        out.text,
        "  \"{}\": {bot_deleted};",
        notification::BOT_DELETED
    );
    let _ = writeln!(
        out.text,
        "  \"{}\": {};",
        notification::FOLDER_RECYCLED,
        out.name::<FolderRecycled>()
    );
    let state = out.name::<BotStateChanged>();
    let item = out.name::<ChatItemChanged>();
    let delta = out.name::<ChatDelta>();
    let _ = writeln!(out.text, "  \"{}\": {state};", notification::BOT_STATE);
    let _ = writeln!(out.text, "  \"{}\": {item};", notification::CHAT_ITEM);
    let _ = writeln!(out.text, "  \"{}\": {delta};", notification::CHAT_DELTA);
    let task = out.name::<Task>();
    let _ = writeln!(
        out.text,
        "  \"{}\": {message};",
        notification::MESSAGE_CREATED
    );
    let _ = writeln!(
        out.text,
        "  \"{}\": {delivery};",
        notification::DELIVERY_CHANGED
    );
    let _ = writeln!(out.text, "  \"{}\": {task};", notification::TASK_CHANGED);
    session::notifications(&mut out);
    routines::notifications(&mut out);
    questions::notifications(&mut out);
    reactions::notifications(&mut out);
    rules::notifications(&mut out);
    desktop::notifications(&mut out);
    mcp::notifications(&mut out);
    cloud::notifications(&mut out);
    mobile::notifications(&mut out);
    browser::notifications(&mut out);
    out.text.push_str("}\n\n");

    out.text.push_str("export const RpcErrorCode = {\n");
    for (name, code) in [
        ("parseError", error_code::PARSE_ERROR),
        ("invalidRequest", error_code::INVALID_REQUEST),
        ("methodNotFound", error_code::METHOD_NOT_FOUND),
        ("invalidParams", error_code::INVALID_PARAMS),
        ("internalError", error_code::INTERNAL_ERROR),
        ("notAuthenticated", error_code::NOT_AUTHENTICATED),
        ("notFound", error_code::NOT_FOUND),
        ("conflict", error_code::CONFLICT),
        ("validation", error_code::VALIDATION),
        ("runtimeUnavailable", error_code::RUNTIME_UNAVAILABLE),
    ] {
        let _ = writeln!(out.text, "  {name}: {code},");
    }
    out.text.push_str("} as const;\n");

    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../app/src/lib/protocol.gen.ts");
    std::fs::write(&path, out.text).expect("write protocol.gen.ts");
}
