//! Writes `app/src/lib/protocol.gen.ts`. Run it with
//! `cargo test -p botloft-core export_bindings`; CI fails if the committed
//! file differs from what this produces.

use std::fmt::Write as _;
use std::path::Path;

use ts_rs::{Config, TS};

use super::*;
use crate::ids::{BotId, CrewId, DeliveryId, MessageId, TaskId};

const HEADER: &str = "\
// Generated by `cargo test -p botloft-core export_bindings`. Do not edit by hand.
// Source: crates/botloft-core/src/protocol.
";

struct Out {
    cfg: Config,
    text: String,
}

impl Out {
    fn decl<T: TS>(&mut self) {
        if let Some(docs) = T::docs() {
            self.text.push_str(&docs);
        }
        let _ = writeln!(self.text, "export {}\n", T::decl(&self.cfg));
    }

    fn method(&mut self, name: &str, params: &str, result: &str) {
        let _ = writeln!(
            self.text,
            "  \"{name}\": {{ params: {params}; result: {result} }};"
        );
    }

    fn name<T: TS>(&self) -> String {
        T::name(&self.cfg)
    }
}

#[test]
fn export_bindings() {
    let mut out = Out {
        cfg: Config::new().with_large_int("number"),
        text: String::from(HEADER),
    };
    let _ = writeln!(
        out.text,
        "\nexport const PROTOCOL_VERSION = {PROTOCOL_VERSION};\n"
    );

    out.decl::<CrewId>();
    out.decl::<BotId>();
    out.decl::<MessageId>();
    out.decl::<DeliveryId>();
    out.decl::<TaskId>();
    out.decl::<Crew>();
    out.decl::<BotState>();
    out.decl::<Bot>();
    out.decl::<ClientInfo>();
    out.decl::<HelloParams>();
    out.decl::<HelloResult>();
    out.decl::<DeliveryBacklog>();
    out.decl::<SystemStatus>();
    out.decl::<CrewsCreateParams>();
    out.decl::<CrewsRenameParams>();
    out.decl::<CrewsSetPausedParams>();
    out.decl::<CrewIdParams>();
    out.decl::<BotsListParams>();
    out.decl::<BotsCreateParams>();
    out.decl::<BotsUpdateParams>();
    out.decl::<BotsSetPausedParams>();
    out.decl::<BotIdParams>();
    out.decl::<BotsRestartParams>();
    out.decl::<BotStateChanged>();
    out.decl::<TerminalAttachParams>();
    out.decl::<TerminalAttachResult>();
    out.decl::<TerminalWriteParams>();
    out.decl::<TerminalResizeParams>();
    out.decl::<TerminalData>();
    out.decl::<SenderKind>();
    out.decl::<MessageKind>();
    out.decl::<DeliveryState>();
    out.decl::<TaskStatus>();
    out.decl::<Message>();
    out.decl::<Delivery>();
    out.decl::<Task>();
    out.decl::<MessagesSendParams>();
    out.decl::<MessagesListParams>();
    out.decl::<DeliveriesListParams>();
    out.decl::<DeliveryIdParams>();

    let crew = out.name::<Crew>();
    let bot = out.name::<Bot>();
    let crews = out.name::<Vec<Crew>>();
    let bots = out.name::<Vec<Bot>>();

    out.text
        .push_str("/** Params and result of every request method. */\n");
    out.text.push_str("export interface RpcMethods {\n");
    out.method(
        method::SESSION_HELLO,
        &out.name::<HelloParams>(),
        &out.name::<HelloResult>(),
    );
    out.method(
        method::SYSTEM_STATUS,
        "undefined",
        &out.name::<SystemStatus>(),
    );
    out.method(method::CREWS_LIST, "undefined", &crews);
    out.method(
        method::CREWS_CREATE,
        &out.name::<CrewsCreateParams>(),
        &crew,
    );
    out.method(
        method::CREWS_RENAME,
        &out.name::<CrewsRenameParams>(),
        &crew,
    );
    out.method(
        method::CREWS_SET_PAUSED,
        &out.name::<CrewsSetPausedParams>(),
        &crew,
    );
    out.method(method::CREWS_ARCHIVE, &out.name::<CrewIdParams>(), &crew);
    out.method(method::BOTS_LIST, &out.name::<BotsListParams>(), &bots);
    out.method(method::BOTS_CREATE, &out.name::<BotsCreateParams>(), &bot);
    out.method(method::BOTS_UPDATE, &out.name::<BotsUpdateParams>(), &bot);
    out.method(
        method::BOTS_SET_PAUSED,
        &out.name::<BotsSetPausedParams>(),
        &bot,
    );
    out.method(method::BOTS_ARCHIVE, &out.name::<BotIdParams>(), &bot);
    out.method(method::BOTS_RESTART, &out.name::<BotsRestartParams>(), &bot);
    let attach = out.name::<TerminalAttachResult>();
    out.method(
        method::TERMINAL_ATTACH,
        &out.name::<TerminalAttachParams>(),
        &attach,
    );
    out.method(method::TERMINAL_DETACH, &out.name::<BotIdParams>(), "null");
    out.method(
        method::TERMINAL_WRITE,
        &out.name::<TerminalWriteParams>(),
        "null",
    );
    out.method(
        method::TERMINAL_RESIZE,
        &out.name::<TerminalResizeParams>(),
        "null",
    );
    let message = out.name::<Message>();
    let delivery = out.name::<Delivery>();
    out.method(
        method::MESSAGES_SEND,
        &out.name::<MessagesSendParams>(),
        &message,
    );
    out.method(
        method::MESSAGES_LIST,
        &out.name::<MessagesListParams>(),
        &out.name::<Vec<Message>>(),
    );
    out.method(
        method::DELIVERIES_LIST,
        &out.name::<DeliveriesListParams>(),
        &out.name::<Vec<Delivery>>(),
    );
    out.method(
        method::DELIVERIES_RETRY,
        &out.name::<DeliveryIdParams>(),
        &delivery,
    );
    out.text.push_str("}\n\n");

    out.text
        .push_str("/** Params of every server notification. */\n");
    out.text.push_str("export interface RpcNotifications {\n");
    let _ = writeln!(out.text, "  \"{}\": {crew};", notification::CREW_CHANGED);
    let _ = writeln!(out.text, "  \"{}\": {bot};", notification::BOT_CHANGED);
    let state = out.name::<BotStateChanged>();
    let data = out.name::<TerminalData>();
    let _ = writeln!(out.text, "  \"{}\": {state};", notification::BOT_STATE);
    let _ = writeln!(out.text, "  \"{}\": {data};", notification::TERMINAL_DATA);
    let task = out.name::<Task>();
    let _ = writeln!(
        out.text,
        "  \"{}\": {message};",
        notification::MESSAGE_CREATED
    );
    let _ = writeln!(
        out.text,
        "  \"{}\": {delivery};",
        notification::DELIVERY_CHANGED
    );
    let _ = writeln!(out.text, "  \"{}\": {task};", notification::TASK_CHANGED);
    out.text.push_str("}\n\n");

    out.text.push_str("export const RpcErrorCode = {\n");
    for (name, code) in [
        ("parseError", error_code::PARSE_ERROR),
        ("invalidRequest", error_code::INVALID_REQUEST),
        ("methodNotFound", error_code::METHOD_NOT_FOUND),
        ("invalidParams", error_code::INVALID_PARAMS),
        ("internalError", error_code::INTERNAL_ERROR),
        ("notAuthenticated", error_code::NOT_AUTHENTICATED),
        ("notFound", error_code::NOT_FOUND),
        ("conflict", error_code::CONFLICT),
        ("validation", error_code::VALIDATION),
        ("runtimeUnavailable", error_code::RUNTIME_UNAVAILABLE),
    ] {
        let _ = writeln!(out.text, "  {name}: {code},");
    }
    out.text.push_str("} as const;\n");

    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../app/src/lib/protocol.gen.ts");
    std::fs::write(&path, out.text).expect("write protocol.gen.ts");
}
