//! Types of the app <-> daemon JSON-RPC protocol (spec section 11). The app
//! receives them as TypeScript in `app/src/lib/protocol.gen.ts`, generated by
//! `cargo test -p botloft-core export_bindings`.

/// A stored value that is not one of the enum's names.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("unknown {kind} `{value}`")]
pub struct UnknownVariant {
    kind: &'static str,
    value: String,
}

/// Enums stored as text: `as_str` for writing, `FromStr` for reading back.
/// The names match the serde names the app sees.
macro_rules! text_enum {
    ($(#[$doc:meta])* $name:ident, $kind:literal { $($(#[$vdoc:meta])* $variant:ident => $text:literal),+ $(,)? }) => {
        $(#[$doc])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, ::serde::Serialize, ::serde::Deserialize)]
        #[serde(rename_all = "snake_case")]
        #[cfg_attr(test, derive(ts_rs::TS))]
        pub enum $name {
            $($(#[$vdoc])* $variant),+
        }

        impl $name {
            pub fn as_str(self) -> &'static str {
                match self {
                    $(Self::$variant => $text),+
                }
            }
        }

        impl ::std::str::FromStr for $name {
            type Err = $crate::protocol::UnknownVariant;

            fn from_str(s: &str) -> Result<Self, Self::Err> {
                match s {
                    $($text => Ok(Self::$variant),)+
                    _ => Err($crate::protocol::UnknownVariant { kind: $kind, value: s.to_owned() }),
                }
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str(self.as_str())
            }
        }
    };
}

mod backup;
mod browser;
mod browser_input;
mod catalog;
mod chat;
mod cloud;
mod crew_access;
mod desktop;
#[cfg(test)]
mod export;
mod files;
mod lesson;
mod mcp;
mod messaging;
mod methods;
mod model;
mod questions;
mod reactions;
mod routines;
mod rules;
mod screens;
mod search;
mod session;
mod settings;
mod usage;

pub use backup::*;
pub use browser::*;
pub use browser_input::*;
pub use catalog::*;
pub use chat::*;
pub use cloud::*;
pub use crew_access::*;
pub use desktop::*;
pub use files::*;
pub use lesson::*;
pub use mcp::*;
pub use messaging::*;
pub use methods::*;
pub use model::*;
pub use questions::*;
pub use reactions::*;
pub use routines::*;
pub use rules::*;
pub use screens::*;
pub use search::*;
pub use session::*;
pub use settings::*;
pub use usage::*;

/// Version negotiated in `session.hello`. 2 replaced the terminal with the
/// chat (ADR 0001).
pub const PROTOCOL_VERSION: u32 = 2;

/// Request method names.
pub mod method {
    pub const SESSION_HELLO: &str = "session.hello";
    pub const SESSION_SET_LOCALE: &str = "session.setLocale";
    pub const SYSTEM_STATUS: &str = "system.status";
    pub const SYSTEM_REFRESH: &str = "system.refresh";
    pub const CREWS_LIST: &str = "crews.list";
    pub const CREWS_CREATE: &str = "crews.create";
    pub const CREWS_RENAME: &str = "crews.rename";
    pub const CREWS_SET_PAUSED: &str = "crews.setPaused";
    pub const CREWS_SET_WORK_FOLDER: &str = "crews.setWorkFolder";
    pub const CREWS_SET_LEAD: &str = "crews.setLead";
    pub const CREWS_ARCHIVE: &str = "crews.archive";
    pub const CREWS_DELETE: &str = "crews.delete";
    pub const ARCHIVE_LIST: &str = "archive.list";
    pub const BOTS_LIST: &str = "bots.list";
    pub const BOTS_CREATE: &str = "bots.create";
    pub const CATALOG_LIST: &str = "catalog.list";
    pub const CATALOG_GET: &str = "catalog.get";
    pub const CATALOG_ADD: &str = "catalog.add";
    pub const BOTS_UPDATE: &str = "bots.update";
    pub const BOTS_SET_PAUSED: &str = "bots.setPaused";
    pub const BOTS_SET_PERMISSION_MODE: &str = "bots.setPermissionMode";
    pub const BOTS_SET_MODEL: &str = "bots.setModel";
    pub const BOTS_SET_EFFORT: &str = "bots.setEffort";
    pub const BOTS_COMPACT: &str = "bots.compact";
    pub const BOTS_ARCHIVE: &str = "bots.archive";
    pub const BOTS_DELETE: &str = "bots.delete";
    pub const BOTS_RESTART: &str = "bots.restart";
    pub const CHAT_HISTORY: &str = "chat.history";
    pub const CHAT_SEARCH: &str = "chat.search";
    pub const APPROVALS_ANSWER: &str = "approvals.answer";
    pub const RULES_LIST: &str = "rules.list";
    pub const RULES_DELETE: &str = "rules.delete";
    pub const BACKUP_EXPORT: &str = "backup.export";
    pub const BACKUP_STAGE: &str = "backup.stage";
    pub const BACKUP_CONFIRM: &str = "backup.confirm";
    pub const BACKUP_CANCEL: &str = "backup.cancel";
    pub const CLOUD_STATUS: &str = "cloud.status";
    pub const CLOUD_SIGNIN: &str = "cloud.signin";
    pub const CLOUD_SIGNIN_CANCEL: &str = "cloud.signin_cancel";
    pub const CLOUD_SIGNOUT: &str = "cloud.signout";
    pub const CLOUD_UPLOAD: &str = "cloud.upload";
    pub const CLOUD_COPIES: &str = "cloud.copies";
    pub const CLOUD_DOWNLOAD: &str = "cloud.download";
    pub const CLOUD_DELETE: &str = "cloud.delete";
    pub const CLOUD_DELETE_ACCOUNT: &str = "cloud.delete_account";
    pub const CREW_ACCESS_LIST: &str = "crewAccess.list";
    pub const CREW_ACCESS_REVOKE: &str = "crewAccess.revoke";
    pub const MCP_SERVERS: &str = "mcp.servers";
    pub const MCP_SAVE: &str = "mcp.save";
    pub const MCP_DELETE: &str = "mcp.delete";
    pub const BOT_MCP_SET: &str = "bot.mcp.set";
    pub const DESKTOP_GRANTS: &str = "desktop.grants";
    pub const DESKTOP_REVOKE: &str = "desktop.revoke";
    pub const DESKTOP_SET_OPTIONS: &str = "desktop.setOptions";
    pub const DESKTOP_GRANT_WHOLE: &str = "desktop.grantWhole";
    pub const DESKTOP_WATCH: &str = "desktop.watch";
    pub const DESKTOP_UNWATCH: &str = "desktop.unwatch";
    pub const DESKTOP_STOP: &str = "desktop.stop";
    pub const DESKTOP_RESUME: &str = "desktop.resume";
    pub const DESKTOP_AWAY_USES: &str = "desktop.awayUses";
    pub const DESKTOP_DISMISS_AWAY: &str = "desktop.dismissAway";
    pub const MESSAGES_SEND: &str = "messages.send";
    pub const MESSAGES_LIST: &str = "messages.list";
    pub const ATTACHMENTS_READ: &str = "attachments.read";
    pub const FILES_LIST: &str = "files.list";
    pub const FILES_READ: &str = "files.read";
    pub const DELIVERIES_LIST: &str = "deliveries.list";
    pub const DELIVERIES_RETRY: &str = "deliveries.retry";
    pub const TASKS_LIST: &str = "tasks.list";
    pub const ROUTINES_LIST: &str = "routines.list";
    pub const ROUTINES_CREATE: &str = "routines.create";
    pub const ROUTINES_UPDATE: &str = "routines.update";
    pub const ROUTINES_SET_ENABLED: &str = "routines.setEnabled";
    pub const ROUTINES_RUN_NOW: &str = "routines.runNow";
    pub const ROUTINES_ARCHIVE: &str = "routines.archive";
    pub const ROUTINES_RUNS: &str = "routines.runs";
    pub const BROWSER_LIST: &str = "browser.list";
    pub const BROWSER_WATCH: &str = "browser.watch";
    pub const BROWSER_UNWATCH: &str = "browser.unwatch";
    pub const BROWSER_RESIZE: &str = "browser.resize";
    pub const BROWSER_TAKE: &str = "browser.take";
    pub const BROWSER_RELEASE: &str = "browser.release";
    pub const BROWSER_INPUT: &str = "browser.input";
    pub const BROWSER_RELOAD: &str = "browser.reload";
    pub const BROWSER_NEW_TAB: &str = "browser.newTab";
    pub const BROWSER_SWITCH_TAB: &str = "browser.switchTab";
    pub const BROWSER_OPEN: &str = "browser.open";
    pub const BROWSER_WINDOW: &str = "browser.window";
    pub const BROWSER_TEACH: &str = "browser.teach";
    /// The owner opens the bot's closed browser for themselves.
    pub const BROWSER_START: &str = "browser.start";
    pub const SCREENS_LIST: &str = "screens.list";
    pub const QUESTIONS_LIST: &str = "questions.list";
    pub const QUESTIONS_ANSWER: &str = "questions.answer";
    pub const QUESTIONS_DISMISS: &str = "questions.dismiss";
    pub const REACTIONS_LIST: &str = "reactions.list";
    pub const REACTIONS_SET: &str = "reactions.set";
    pub const SETTINGS_GET: &str = "settings.get";
    pub const SETTINGS_UPDATE: &str = "settings.update";
    pub const USAGE_TOKENS: &str = "usage.tokens";
}

/// Server notification method names.
pub mod notification {
    pub const CREW_CHANGED: &str = "crew.changed";
    pub const CREW_DELETED: &str = "crew.deleted";
    pub const BOT_CHANGED: &str = "bot.changed";
    pub const BOT_DELETED: &str = "bot.deleted";
    pub const FOLDER_RECYCLED: &str = "folder.recycled";
    pub const BOT_STATE: &str = "bot.state";
    pub const BOT_CONTEXT: &str = "bot.context";
    pub const BOT_RULES: &str = "bot.rules";
    pub const BOT_DESKTOP: &str = "bot.desktop";
    pub const MCP_SERVERS: &str = "mcp.servers";
    pub const BOT_MCP: &str = "bot.mcp";
    pub const DESKTOP_CHANGED: &str = "desktop.changed";
    /// What bots did while the owner was away, whenever it changes.
    pub const DESKTOP_AWAY: &str = "desktop.away";
    /// Only to the connection watching that bot's desktop panel (spec 24.9).
    pub const DESKTOP_FRAME: &str = "desktop.frame";
    pub const CHAT_ITEM: &str = "chat.item";
    pub const CHAT_DELTA: &str = "chat.delta";
    pub const MESSAGE_CREATED: &str = "message.created";
    pub const DELIVERY_CHANGED: &str = "delivery.changed";
    pub const TASK_CHANGED: &str = "task.changed";
    pub const ROUTINE_CHANGED: &str = "routine.changed";
    pub const ROUTINE_RUN: &str = "routine.run";
    pub const BROWSER_CHANGED: &str = "browser.changed";
    pub const BROWSER_ACTION: &str = "browser.action";
    /// Only to the connection watching that bot's browser (spec 21.7).
    pub const BROWSER_FRAME: &str = "browser.frame";
    pub const SCREEN_DRAFT: &str = "screen.draft";
    pub const QUESTION_CHANGED: &str = "question.changed";
    pub const REACTION_CHANGED: &str = "reaction.changed";
    pub const CLOUD_SIGNED_IN: &str = "cloud.signed_in";
    pub const CLOUD_PROGRESS: &str = "cloud.progress";
    pub const CLOUD_SIGNIN_EXPIRED: &str = "cloud.signin_expired";
}

/// Error codes: the standard JSON-RPC ones plus the daemon's (spec 11.4).
pub mod error_code {
    pub const PARSE_ERROR: i32 = -32700;
    pub const INVALID_REQUEST: i32 = -32600;
    pub const METHOD_NOT_FOUND: i32 = -32601;
    pub const INVALID_PARAMS: i32 = -32602;
    pub const INTERNAL_ERROR: i32 = -32603;
    pub const NOT_AUTHENTICATED: i32 = -32001;
    pub const NOT_FOUND: i32 = -32002;
    pub const CONFLICT: i32 = -32003;
    pub const VALIDATION: i32 = -32004;
    pub const RUNTIME_UNAVAILABLE: i32 = -32005;
}
