//! Types of the app <-> daemon JSON-RPC protocol (spec section 11). The app
//! receives them as TypeScript in `app/src/lib/protocol.gen.ts`, generated by
//! `cargo test -p botloft-core export_bindings`.

/// A stored value that is not one of the enum's names.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("unknown {kind} `{value}`")]
pub struct UnknownVariant {
    kind: &'static str,
    value: String,
}

/// Enums stored as text: `as_str` for writing, `FromStr` for reading back.
/// The names match the serde names the app sees.
macro_rules! text_enum {
    ($(#[$doc:meta])* $name:ident, $kind:literal { $($(#[$vdoc:meta])* $variant:ident => $text:literal),+ $(,)? }) => {
        $(#[$doc])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, ::serde::Serialize, ::serde::Deserialize)]
        #[serde(rename_all = "snake_case")]
        #[cfg_attr(test, derive(ts_rs::TS))]
        pub enum $name {
            $($(#[$vdoc])* $variant),+
        }

        impl $name {
            pub fn as_str(self) -> &'static str {
                match self {
                    $(Self::$variant => $text),+
                }
            }
        }

        impl ::std::str::FromStr for $name {
            type Err = $crate::protocol::UnknownVariant;

            fn from_str(s: &str) -> Result<Self, Self::Err> {
                match s {
                    $($text => Ok(Self::$variant),)+
                    _ => Err($crate::protocol::UnknownVariant { kind: $kind, value: s.to_owned() }),
                }
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str(self.as_str())
            }
        }
    };
}

mod browser;
mod browser_input;
mod chat;
#[cfg(test)]
mod export;
mod files;
mod messaging;
mod methods;
mod model;
mod routines;
mod screens;

pub use browser::*;
pub use browser_input::*;
pub use chat::*;
pub use files::*;
pub use messaging::*;
pub use methods::*;
pub use model::*;
pub use routines::*;
pub use screens::*;

/// Version negotiated in `session.hello`. 2 replaced the terminal with the
/// chat (ADR 0001).
pub const PROTOCOL_VERSION: u32 = 2;

/// Request method names.
pub mod method {
    pub const SESSION_HELLO: &str = "session.hello";
    pub const SYSTEM_STATUS: &str = "system.status";
    pub const SYSTEM_REFRESH: &str = "system.refresh";
    pub const CREWS_LIST: &str = "crews.list";
    pub const CREWS_CREATE: &str = "crews.create";
    pub const CREWS_RENAME: &str = "crews.rename";
    pub const CREWS_SET_PAUSED: &str = "crews.setPaused";
    pub const CREWS_SET_WORK_FOLDER: &str = "crews.setWorkFolder";
    pub const CREWS_SET_LEAD: &str = "crews.setLead";
    pub const CREWS_ARCHIVE: &str = "crews.archive";
    pub const BOTS_LIST: &str = "bots.list";
    pub const BOTS_CREATE: &str = "bots.create";
    pub const BOTS_UPDATE: &str = "bots.update";
    pub const BOTS_SET_PAUSED: &str = "bots.setPaused";
    pub const BOTS_SET_PERMISSION_MODE: &str = "bots.setPermissionMode";
    pub const BOTS_SET_MODEL: &str = "bots.setModel";
    pub const BOTS_ARCHIVE: &str = "bots.archive";
    pub const BOTS_RESTART: &str = "bots.restart";
    pub const CHAT_HISTORY: &str = "chat.history";
    pub const APPROVALS_ANSWER: &str = "approvals.answer";
    pub const MESSAGES_SEND: &str = "messages.send";
    pub const MESSAGES_LIST: &str = "messages.list";
    pub const ATTACHMENTS_READ: &str = "attachments.read";
    pub const FILES_LIST: &str = "files.list";
    pub const FILES_READ: &str = "files.read";
    pub const DELIVERIES_LIST: &str = "deliveries.list";
    pub const DELIVERIES_RETRY: &str = "deliveries.retry";
    pub const TASKS_LIST: &str = "tasks.list";
    pub const ROUTINES_LIST: &str = "routines.list";
    pub const ROUTINES_CREATE: &str = "routines.create";
    pub const ROUTINES_UPDATE: &str = "routines.update";
    pub const ROUTINES_SET_ENABLED: &str = "routines.setEnabled";
    pub const ROUTINES_RUN_NOW: &str = "routines.runNow";
    pub const ROUTINES_ARCHIVE: &str = "routines.archive";
    pub const ROUTINES_RUNS: &str = "routines.runs";
    pub const BROWSER_LIST: &str = "browser.list";
    pub const BROWSER_WATCH: &str = "browser.watch";
    pub const BROWSER_UNWATCH: &str = "browser.unwatch";
    pub const BROWSER_TAKE: &str = "browser.take";
    pub const BROWSER_RELEASE: &str = "browser.release";
    pub const BROWSER_INPUT: &str = "browser.input";
    pub const SCREENS_LIST: &str = "screens.list";
}

/// Server notification method names.
pub mod notification {
    pub const CREW_CHANGED: &str = "crew.changed";
    pub const BOT_CHANGED: &str = "bot.changed";
    pub const BOT_STATE: &str = "bot.state";
    pub const CHAT_ITEM: &str = "chat.item";
    pub const CHAT_DELTA: &str = "chat.delta";
    pub const MESSAGE_CREATED: &str = "message.created";
    pub const DELIVERY_CHANGED: &str = "delivery.changed";
    pub const TASK_CHANGED: &str = "task.changed";
    pub const ROUTINE_CHANGED: &str = "routine.changed";
    pub const ROUTINE_RUN: &str = "routine.run";
    pub const BROWSER_CHANGED: &str = "browser.changed";
    pub const BROWSER_ACTION: &str = "browser.action";
    /// Only to the connection watching that bot's browser (spec 21.7).
    pub const BROWSER_FRAME: &str = "browser.frame";
    pub const SCREEN_DRAFT: &str = "screen.draft";
}

/// Error codes: the standard JSON-RPC ones plus the daemon's (spec 11.4).
pub mod error_code {
    pub const PARSE_ERROR: i32 = -32700;
    pub const INVALID_REQUEST: i32 = -32600;
    pub const METHOD_NOT_FOUND: i32 = -32601;
    pub const INVALID_PARAMS: i32 = -32602;
    pub const INTERNAL_ERROR: i32 = -32603;
    pub const NOT_AUTHENTICATED: i32 = -32001;
    pub const NOT_FOUND: i32 = -32002;
    pub const CONFLICT: i32 = -32003;
    pub const VALIDATION: i32 = -32004;
    pub const RUNTIME_UNAVAILABLE: i32 = -32005;
}
