//! Types of the app <-> daemon JSON-RPC protocol (spec section 11). The app
//! receives them as TypeScript in `app/src/lib/protocol.gen.ts`, generated by
//! `cargo test -p botloft-core export_bindings`.

#[cfg(test)]
mod export;
mod methods;
mod model;
mod terminal;

pub use methods::*;
pub use model::*;
pub use terminal::*;

/// Version negotiated in `session.hello`.
pub const PROTOCOL_VERSION: u32 = 1;

/// Request method names.
pub mod method {
    pub const SESSION_HELLO: &str = "session.hello";
    pub const SYSTEM_STATUS: &str = "system.status";
    pub const CREWS_LIST: &str = "crews.list";
    pub const CREWS_CREATE: &str = "crews.create";
    pub const CREWS_RENAME: &str = "crews.rename";
    pub const CREWS_SET_PAUSED: &str = "crews.setPaused";
    pub const CREWS_ARCHIVE: &str = "crews.archive";
    pub const BOTS_LIST: &str = "bots.list";
    pub const BOTS_CREATE: &str = "bots.create";
    pub const BOTS_UPDATE: &str = "bots.update";
    pub const BOTS_SET_PAUSED: &str = "bots.setPaused";
    pub const BOTS_ARCHIVE: &str = "bots.archive";
    pub const BOTS_RESTART: &str = "bots.restart";
    pub const TERMINAL_ATTACH: &str = "terminal.attach";
    pub const TERMINAL_DETACH: &str = "terminal.detach";
    pub const TERMINAL_WRITE: &str = "terminal.write";
    pub const TERMINAL_RESIZE: &str = "terminal.resize";
}

/// Server notification method names.
pub mod notification {
    pub const CREW_CHANGED: &str = "crew.changed";
    pub const BOT_CHANGED: &str = "bot.changed";
    pub const BOT_STATE: &str = "bot.state";
    pub const TERMINAL_DATA: &str = "terminal.data";
}

/// Error codes: the standard JSON-RPC ones plus the daemon's (spec 11.4).
pub mod error_code {
    pub const PARSE_ERROR: i32 = -32700;
    pub const INVALID_REQUEST: i32 = -32600;
    pub const METHOD_NOT_FOUND: i32 = -32601;
    pub const INVALID_PARAMS: i32 = -32602;
    pub const INTERNAL_ERROR: i32 = -32603;
    pub const NOT_AUTHENTICATED: i32 = -32001;
    pub const NOT_FOUND: i32 = -32002;
    pub const CONFLICT: i32 = -32003;
    pub const VALIDATION: i32 = -32004;
    pub const RUNTIME_UNAVAILABLE: i32 = -32005;
}
