// Builds @botloft/ui into dist/: an ES module with the components (React
// left external), the app's compiled stylesheet with its fonts, and .d.ts
// files for the converter. Uses the app's own Vite, Tailwind and TypeScript
// from app/node_modules, so the output matches what the app ships.
//
//   node .design-sync/pkg/build.mjs

import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const app = resolve(here, "../../app");
const dist = join(here, "dist");
const require = createRequire(join(app, "package.json"));
const load = async (name) => import(pathToFileURL(require.resolve(name)).href);

rmSync(dist, { recursive: true, force: true });

// The icons the app uses, as `icons.<Name>` (Button takes one as `icon`).
// Read from the app's imports so the set follows the app.
const iconNames = new Set();
const walk = (dir) => {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) walk(path);
    else if (/\.tsx?$/.test(entry.name) && !/\.test\./.test(entry.name)) {
      for (const match of readFileSync(path, "utf8").matchAll(/import \{([^}]*)\} from "lucide-react"/g)) {
        for (const name of match[1].split(",")) {
          const bare = name.replace(/^\s*type\s+/, "").trim();
          if (/^[A-Z]\w*$/.test(bare) && !/^Lucide/.test(bare) && !/^\s*type\s/.test(name)) {
            iconNames.add(bare);
          }
        }
      }
    }
  }
};
walk(join(app, "src"));
const iconsModule = `// Generated by build.mjs from the app's lucide-react imports.\nexport { ${[...iconNames].sort().join(", ")} } from "lucide-react";\n`;
writeFileSync(join(here, "icons.gen.ts"), iconsModule);

const { build } = await load("vite");
const tailwindcss = (await load("@tailwindcss/vite")).default;
const react = (await load("@vitejs/plugin-react")).default;

// Library mode inlines every asset, so the fonts would land in the CSS as
// base64, every alphabet included. They are left out here and ship as
// files instead (cfg.extraFonts: the Latin subsets the app needs).
const noFonts = join(here, ".no-fonts.css");
writeFileSync(noFonts, "");

// The app is the root so Tailwind scans app/src and emits every utility
// the app uses: the design agent can then use the same class vocabulary.
try {
await build({
  root: app,
  configFile: false,
  logLevel: "warn",
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: [
      { find: /^@fontsource\/.*\.css$/, replacement: noFonts },
      // icons.gen.ts sits outside the app, beyond the reach of its node_modules.
      { find: /^lucide-react$/, replacement: join(app, "node_modules", "lucide-react") },
    ],
  },
  build: {
    target: "chrome120",
    outDir: dist,
    emptyOutDir: true,
    minify: false,
    lib: {
      entry: join(here, "index.ts"),
      formats: ["es"],
      fileName: () => "index.js",
      cssFileName: "styles",
    },
    rollupOptions: {
      external: (id) => /^react(-dom)?(\/|$)/.test(id),
    },
  },
});
} finally {
  rmSync(noFonts, { force: true });
}

// Types: declarations for the app files the entry re-exports, then an
// index.d.ts that is the entry with its paths pointed at them.
const entry = readFileSync(join(here, "index.ts"), "utf8");
const sources = [...entry.matchAll(/from "\.\.\/\.\.\/app\/src\/([^"]+)"/g)].map(
  (match) =>
    existsSync(join(app, `src/${match[1]}.tsx`)) ? `src/${match[1]}.tsx` : `src/${match[1]}/index.ts`,
);
const tsconfig = join(here, "tsconfig.types.json");
writeFileSync(
  tsconfig,
  `${JSON.stringify(
    {
      extends: join(app, "tsconfig.json").replaceAll("\\", "/"),
      compilerOptions: {
        noEmit: false,
        declaration: true,
        emitDeclarationOnly: true,
        rootDir: join(app, "src").replaceAll("\\", "/"),
        outDir: join(dist, "types", "app").replaceAll("\\", "/"),
        types: [],
        typeRoots: [join(app, "node_modules", "@types").replaceAll("\\", "/")],
      },
      files: sources.map((source) => join(app, source).replaceAll("\\", "/")),
      include: [],
    },
    null,
    2,
  )}\n`,
);
try {
  const tsc = join(dirname(require.resolve("typescript/package.json")), "bin", "tsc");
  execFileSync(process.execPath, [tsc, "-p", tsconfig], {
    stdio: "inherit",
  });
} finally {
  rmSync(tsconfig, { force: true });
}
writeFileSync(
  join(dist, "types", "index.d.ts"),
  entry
    .split("\n")
    .filter((line) => !line.startsWith("import ") && !line.startsWith("//"))
    .join("\n")
    .replaceAll("../../app/src/", "./app/")
    .trimStart(),
);
writeFileSync(join(dist, "types", "icons.gen.d.ts"), iconsModule);
console.log(`built ${dist}`);
