// Generated by `cargo test -p botloft-core export_bindings`. Do not edit by hand.
// Source: crates/botloft-core/src/protocol.

export const PROTOCOL_VERSION = 2;

/** Avatar colors the daemon assigns in order (spec 15.3). */
export const AVATAR_PALETTE = ["#FF7A59", "#5EC8FF", "#A48BFF", "#9BE564", "#FFC857", "#FF7EB6", "#3DD9C1", "#E8D5B0", "#F25F5C", "#4C7BFF", "#E26BE0", "#3FBF6F", "#FF9F43", "#8C9BB0", "#B07A54", "#E9EEF2"] as const;

/** Longest values the daemon accepts, in characters (files, for attachments). */
export const FIELD_LIMITS = {
  name: 64,
  role: 200,
  instructions: 32000,
  message: 100000,
  attachments: 10,
} as const;

/**
 * Identifies a crew.
 */
export type CrewId = string;

/**
 * Identifies a bot.
 */
export type BotId = string;

/**
 * Identifies a message.
 */
export type MessageId = string;

/**
 * Identifies a delivery attempt record.
 */
export type DeliveryId = string;

/**
 * Identifies a task between bots.
 */
export type TaskId = string;

/**
 * Identifies an item of a bot's chat.
 */
export type ChatItemId = string;

/**
 * Identifies a permission request waiting for the owner.
 */
export type ApprovalId = string;

/**
 * Identifies a file the owner attached to a message.
 */
export type AttachmentId = string;

/**
 * Identifies a routine (spec 20).
 */
export type RoutineId = string;

/**
 * Identifies one run of a routine.
 */
export type RoutineRunId = string;

/**
 * Identifies a request a bot may make without asking (spec 10.1).
 */
export type RuleId = string;

/**
 * Identifies a question a bot asked the owner (spec 23).
 */
export type QuestionId = string;

/**
 * Identifies what the owner let a bot see or do on their desktop
 * (spec 24.2).
 */
export type DesktopGrantId = string;

/**
 * Identifies a connected tool, an MCP server of the owner (spec 25).
 */
export type McpServerId = string;

/**
 * Identifies what the owner let a bot reach in another crew (spec 10.4).
 */
export type CrewAccessId = string;

/**
 * A group of bots that can message each other and share a folder.
 */
export type Crew = { id: CrewId, name: string, 
/**
 * Folder name under the workspaces root. Set at creation, never changes.
 */
slug: string, 
/**
 * Absolute path of the folder the crew works in (spec 5): one the owner
 * chose, or the crew's `shared` folder.
 */
workFolder: string, 
/**
 * Whether the owner chose `work_folder`.
 */
workFolderChosen: boolean, 
/**
 * The bot that leads the crew and may suggest new bots (spec 10.2);
 * `null` when the crew has no chief.
 */
leadBotId: BotId | null, paused: boolean, 
/**
 * Color `#RRGGBB` the owner gave the crew; `null` for none.
 */
color: string | null, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds; `null` while the crew is active.
 */
archivedAt: number | null, };

/**
 * Lifecycle state of a bot (spec 7.1).
 */
export type BotState = "offline" | "launching" | "idle" | "busy" | "needs_approval" | "rate_limited" | "auth_error" | "backoff" | "archived";

/**
 * How much a bot may do without asking the owner: Claude Code's
 * permission modes (spec 7.4).
 */
export type PermissionMode = "default" | "accept_edits" | "plan" | "auto" | "bypass_permissions";

/**
 * Which agent runs a bot (spec 30). Chosen when the bot is created.
 */
export type AgentKind = "claude" | "codex" | "agy";

/**
 * Which Claude model a bot runs on (spec 7.4): Claude Code's `--model`
 * aliases, or the account's default.
 */
export type BotModel = "default" | "fable" | "opus" | "sonnet" | "haiku";

/**
 * What the conversation-list line shows; the app words it.
 */
export type ActivityKind = "owner" | "message" | "reply" | "tool" | "approval" | "question" | "notice";

/**
 * The last thing in a bot's chat, for the conversation list.
 */
export type Activity = { kind: ActivityKind, 
/**
 * One line, at most 120 characters, without wording of its own: for
 * a tool or a request, what it is about.
 */
text: string, 
/**
 * The tool, for a tool call or a request: the app names it.
 */
tool: string | null, 
/**
 * Unix time in milliseconds.
 */
at: number, };

/**
 * How much a bot thinks before it answers (spec 7.4): Claude Code's
 * `--effort` levels, or the level its model uses by itself.
 */
export type BotEffort = "default" | "low" | "medium" | "high" | "xhigh" | "max";

/**
 * The effort a model runs at when the owner picks none, as Claude Code
 * reports it (spec 7.4).
 */
export type ModelEffort = "none" | "low" | "medium" | "high" | "xhigh" | "max";

/**
 * How full a bot's conversation is, in tokens, as Claude Code counts it
 * (spec 8.6).
 */
export type ContextUsage = { 
/**
 * What the conversation holds now.
 */
usedTokens: number, 
/**
 * The most it can hold.
 */
windowTokens: number, 
/**
 * Where Claude Code compacts the conversation by itself; `null` when it
 * does not.
 */
autoCompactTokens: number | null, 
/**
 * The conversation is being compacted right now.
 */
compacting: boolean, 
/**
 * Unix time in milliseconds.
 */
updatedAt: number, };

/**
 * Params of the `bot.context` notification.
 */
export type BotContextChanged = { botId: BotId, 
/**
 * `null` when the bot began a new conversation and its size is not
 * known yet.
 */
context: ContextUsage | null, };

export type BotsSetEffortParams = { botId: BotId, effort: BotEffort, };

/**
 * A persistent Claude Code session with a name, a role and instructions.
 */
export type Bot = { id: BotId, crewId: CrewId, name: string, 
/**
 * Address other bots use (`send_message(to: "<handle>")`). Derived from
 * the name and unique among the crew's active bots.
 */
handle: string, 
/**
 * Folder name inside the crew folder. Set at creation, never changes.
 */
slug: string, role: string, instructions: string, 
/**
 * Avatar color, `#RRGGBB`.
 */
color: string, paused: boolean, permissionMode: PermissionMode, 
/**
 * The agent behind the bot.
 */
agent: AgentKind, 
/**
 * The model of a bot that does not run on Claude Code, as its agent
 * names it; `null` for the agent's default (spec 30).
 */
agentModel: string | null, 
/**
 * Command prefixes a bot not on Claude Code may run without asking:
 * its agent cannot ask in headless mode (spec 30). `*` is every command.
 */
allowedCommands: Array<string>, model: BotModel, 
/**
 * The model id Claude Code reported when the bot last started a turn
 * (`claude-opus-5-5`); `null` before its first turn.
 */
modelInUse: string | null, effort: BotEffort, 
/**
 * The effort the bot's model uses by itself, as Claude Code last
 * reported it; `null` until it is known.
 */
effortDefault: ModelEffort | null, 
/**
 * How full the conversation is; `null` until Claude Code said so.
 */
context: ContextUsage | null, state: BotState, 
/**
 * Current process generation; `null` if the bot has not started since
 * the daemon did. Changes on every (re)start.
 */
generation: number | null, 
/**
 * Absolute path of the bot's workspace folder.
 */
workspace: string, 
/**
 * The last item of the bot's chat, in one line; `null` for a new bot.
 */
lastActivity: Activity | null, 
/**
 * When the bot last finished a reply, in Unix milliseconds; `null`
 * before its first. The app marks the bot unread when this is newer
 * than the owner's last look (spec 15.1).
 */
lastReplyAt: number | null, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds; `null` while the bot is active.
 */
archivedAt: number | null, };

/**
 * Identifies the connecting app in `session.hello`.
 */
export type ClientInfo = { name: string, version: string, 
/**
 * The language the owner reads the app in ("en", "pt-BR", "es"), for
 * what the daemon itself shows them (spec 24.7).
 */
locale?: string, };

/**
 * First request of every connection.
 */
export type HelloParams = { 
/**
 * Owner token from `secrets\owner.token`.
 */
token: string, client: ClientInfo, protocol: number, };

/**
 * `session.setLocale`: the owner changed the app's language.
 */
export type LocaleParams = { locale: string, };

export type HelloResult = { daemonVersion: string, protocol: number, };

/**
 * Deliveries still to go and those that gave up, for `system.status`.
 */
export type DeliveryBacklog = { 
/**
 * `pending` and `sending`.
 */
pending: number, dead: number, };

export type UsageWindow = { 
/**
 * `five_hour`, `seven_day`...
 */
name: string, 
/**
 * Share used, 0 to 1.
 */
utilization: number, 
/**
 * Unix time in milliseconds.
 */
resetsAt: number | null, };

/**
 * The account's usage, from Claude Code's `rate_limit_event` (spec 8.1).
 */
export type AccountUsage = { 
/**
 * As Claude Code says it: `allowed`, `allowed_warning`, `rejected`...
 */
status: string, 
/**
 * Unix time in milliseconds when the current limit resets.
 */
resetsAt: number | null, windows: Array<UsageWindow>, 
/**
 * Unix time in milliseconds.
 */
observedAt: number, };

/**
 * What `claude auth status` says about the account (spec 7.3).
 */
export type ClaudeAccount = { email: string | null, 
/**
 * As Claude Code says it: `max`, `pro`, `team`, `enterprise`...
 */
plan: string | null, organization: string | null, };

/**
 * The owner, as the app shows them in its account area (spec 15.1).
 */
export type OwnerAccount = { 
/**
 * The Windows account's display name, or the user name without one.
 */
name: string, 
/**
 * The Claude account Claude Code is signed in to; `null` when signed out
 * or not checked yet.
 */
claude: ClaudeAccount | null, };

export type SystemStatus = { daemonVersion: string, protocol: number, uptimeMs: number, 
/**
 * Version reported by `claude --version`; `null` until the runtime probe runs.
 */
claudeVersion: string | null, 
/**
 * Why bots cannot start (Claude Code missing or too old); `null` when fine.
 */
runtimeError: string | null, 
/**
 * The Claude Code executable the bots run; `null` until it is found.
 */
claudePath: string | null, 
/**
 * Whether Claude Code is signed in (`claude auth status`); `null` until checked.
 */
claudeSignedIn: boolean | null, 
/**
 * Who the owner is, for the account area of the app.
 */
account: OwnerAccount, deliveries: DeliveryBacklog, 
/**
 * The Claude account's usage as last reported; `null` before any turn.
 */
usage: AccountUsage | null, 
/**
 * The agents a bot may be made for (spec 30): Claude Code, and the
 * experimental ones the owner switched on.
 */
enabledAgents: Array<AgentKind>, 
/**
 * Whether each enabled agent other than Claude Code is installed
 * (spec 30). Claude Code has its own fields above.
 */
agentChecks: Array<AgentCheck>, };

export type CrewsCreateParams = { name: string, 
/**
 * Absolute path of the folder the crew works in; the crew's `shared`
 * folder when absent.
 */
workFolder?: string, 
/**
 * The chief, created with the crew (spec 10.2).
 */
lead?: NewLead, };

export type CrewsRenameParams = { crewId: CrewId, name: string, };

export type CrewsSetColorParams = { crewId: CrewId, 
/**
 * `#RRGGBB`; `null` clears the color.
 */
color: string | null, };

export type CrewsSetPausedParams = { crewId: CrewId, paused: boolean, };

export type CrewsSetWorkFolderParams = { crewId: CrewId, 
/**
 * `null` goes back to the crew's `shared` folder.
 */
workFolder: string | null, };

/**
 * The bot that leads a new crew. The app writes its name and role in the
 * owner's language; the instructions carry the crew's goal.
 */
export type NewLead = { name: string, role: string, instructions: string, model?: BotModel, };

export type CrewsSetLeadParams = { crewId: CrewId, 
/**
 * `null` leaves the crew without a chief.
 */
botId: BotId | null, };

export type CrewIdParams = { crewId: CrewId, };

export type BotsListParams = { 
/**
 * Only bots of this crew; every active bot when absent.
 */
crewId?: CrewId, };

export type BotsCreateParams = { crewId: CrewId, name: string, role: string, instructions: string, 
/**
 * Avatar color `#RRGGBB`; the next palette color when absent.
 */
color?: string, 
/**
 * The account's default when absent.
 */
model?: BotModel, 
/**
 * `claude` when absent.
 */
agent?: AgentKind, };

/**
 * Fields left out stay unchanged.
 */
export type BotsUpdateParams = { botId: BotId, name?: string, role?: string, instructions?: string, color?: string, 
/**
 * For a bot not on Claude Code; replaces the whole list.
 */
allowedCommands?: Array<string>, };

export type BotsSetPausedParams = { botId: BotId, paused: boolean, };

export type BotsSetPermissionModeParams = { botId: BotId, mode: PermissionMode, };

export type BotsSetModelParams = { botId: BotId, model: BotModel, };

/**
 * Params of `bots.setAgentModel` (spec 30).
 */
export type BotsSetAgentModelParams = { botId: BotId, 
/**
 * An id from `agents.models`; `null` goes back to the agent's default.
 */
model: string | null, };

/**
 * Params of `agents.models`.
 */
export type AgentsModelsParams = { agent: AgentKind, };

/**
 * A model an agent offers.
 */
export type AgentModel = { id: string, 
/**
 * As the agent names it for people.
 */
name: string, };

/**
 * What looking for an agent's program found.
 */
export type AgentCheck = { agent: AgentKind, 
/**
 * What `--version` said; `null` when the program was not found or did
 * not answer.
 */
version: string | null, };

export type BotIdParams = { botId: BotId, };

export type BotsRestartParams = { botId: BotId, 
/**
 * Start a new conversation instead of resuming the last one.
 */
fresh?: boolean, };

/**
 * Params of the `bot.state` notification.
 */
export type BotStateChanged = { botId: BotId, state: BotState, generation: number | null, };

/**
 * A bot that was deleted for good (spec 7.6): the result of `bots.delete`
 * and the params of the `bot.deleted` notification.
 */
export type BotDeleted = { botId: BotId, crewId: CrewId, };

/**
 * A crew that was deleted with every bot in it (spec 7.6): the result of
 * `crews.delete` and the params of the `crew.deleted` notification.
 */
export type CrewDeleted = { crewId: CrewId, };

/**
 * What the owner archived (`archive.list`): out of the app, kept in the
 * database, and still there to delete (spec 7.6). `bots` has every
 * archived bot, those of archived crews too.
 */
export type Archive = { crews: Array<Crew>, bots: Array<Bot>, };

/**
 * Params of `bots.delete` (spec 7.6).
 */
export type BotsDeleteParams = { botId: BotId, 
/**
 * Also move the bot's folder to the Recycle Bin; it stays when absent.
 */
recycleFolder?: boolean, };

/**
 * Params of `crews.delete` (spec 7.6).
 */
export type CrewsDeleteParams = { crewId: CrewId, 
/**
 * Also move the crew's own folder, with each bot's folder and
 * `shared`, to the Recycle Bin; it stays when absent. A work folder
 * the owner chose is never moved.
 */
recycleFolder?: boolean, };

/**
 * Params of the `folder.recycled` notification: how the move of a deleted
 * bot's or crew's folder to the Recycle Bin ended (spec 7.6).
 */
export type FolderRecycled = { 
/**
 * Absolute path the folder had.
 */
path: string, 
/**
 * Why the folder is still there; `null` when it is in the bin.
 */
error: string | null, };

/**
 * Who wrote a message.
 */
export type SenderKind = "owner" | "bot" | "system";

/**
 * What a message is for.
 */
export type MessageKind = "note" | "task" | "result" | "system" | "routine";

/**
 * Where a delivery is in the courier (spec 9.1).
 */
export type DeliveryState = "pending" | "sending" | "sent" | "dead";

export type TaskStatus = "open" | "done" | "failed" | "cancelled" | "expired";

/**
 * A file attached to a message, saved in the bot's folder.
 */
export type Attachment = { id: AttachmentId, 
/**
 * File name as saved, without folders.
 */
name: string, mediaType: string, 
/**
 * Bytes.
 */
size: number, 
/**
 * Path relative to the bot's workspace, with forward slashes.
 */
path: string, };

/**
 * A file the owner sends with `messages.send`.
 */
export type AttachmentUpload = { name: string, mediaType: string, 
/**
 * The file's bytes, base64.
 */
data: string, };

export type AttachmentIdParams = { attachmentId: AttachmentId, };

/**
 * A saved attachment's bytes, for the app to show (spec 9.5).
 */
export type AttachmentData = { mediaType: string, 
/**
 * The file's bytes, base64.
 */
data: string, };

/**
 * A file in the bot's folder or the crew's work folder, or one the bot's
 * own `Write`/`Edit` calls changed.
 */
export type BotFile = { 
/**
 * Absolute path.
 */
path: string, 
/**
 * File name, without folders.
 */
name: string, 
/**
 * Folder it is in, relative to the work folder or the bot's folder when
 * it is inside one, else the absolute folder; empty at the top.
 */
folder: string, 
/**
 * Guessed from the extension.
 */
mediaType: string, 
/**
 * Bytes.
 */
size: number, 
/**
 * Unix time in milliseconds.
 */
modifiedAt: number, 
/**
 * The bot's own `Write`/`Edit` calls changed it, as opposed to a file
 * that only showed up in the folder.
 */
writtenByBot: boolean, };

export type FilesListParams = { botId: BotId, };

export type FilesReadParams = { botId: BotId, 
/**
 * A `BotFile.path`.
 */
path: string, };

/**
 * A file's bytes, for the app to preview.
 */
export type FileData = { mediaType: string, 
/**
 * The file's bytes, base64.
 */
data: string, };

/**
 * Text sent to a bot, by the owner, another bot or the daemon.
 */
export type Message = { id: MessageId, crewId: CrewId, fromKind: SenderKind, 
/**
 * Set when `fromKind` is `bot`.
 */
fromBotId: BotId | null, toBotId: BotId, kind: MessageKind, body: string, 
/**
 * The task this message asks for, answers or reports on.
 */
taskId: TaskId | null, 
/**
 * The routine that sent it (spec 20.5).
 */
routineId: RoutineId | null, 
/**
 * The bot's question this message answers (spec 23.4).
 */
questionId: QuestionId | null, 
/**
 * Files the owner attached (spec 9.5); empty for everything else.
 */
attachments: Array<Attachment>, 
/**
 * What in the bot's chat the owner replied to (spec 9.3).
 */
replyTo: MessageReply | null, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, };

/**
 * The chat item a message replies to, and its text as quoted.
 */
export type MessageReply = { itemId: ChatItemId, 
/**
 * The start of the item's text, on one line (at most 300 characters).
 */
text: string, };

/**
 * Getting one message into one bot's process.
 */
export type Delivery = { id: DeliveryId, messageId: MessageId, botId: BotId, state: DeliveryState, 
/**
 * Failed attempts so far. Waiting for the bot to be ready is not one.
 */
attempts: number, 
/**
 * Unix time in milliseconds of the next try while `pending`.
 */
nextAttemptAt: number, 
/**
 * Why the last attempt failed; never contains the message body.
 */
lastError: string | null, 
/**
 * Unix time in milliseconds the bot began the turn for this message.
 */
readAt: number | null, 
/**
 * Unix time in milliseconds.
 */
updatedAt: number, };

/**
 * Work one bot asked another to do (spec 9.4).
 */
export type Task = { id: TaskId, crewId: CrewId, requesterBotId: BotId, assigneeBotId: BotId, status: TaskStatus, 
/**
 * Unix time in milliseconds.
 */
deadlineAt: number, 
/**
 * Position in a chain of delegations: 1 for a task nobody else caused.
 */
hops: number, 
/**
 * First task of the chain this one belongs to; `null` for that first task.
 */
originTaskId: TaskId | null, result: string | null, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds.
 */
updatedAt: number, };

/**
 * The owner writes to a bot.
 */
export type MessagesSendParams = { botId: BotId, body: string, 
/**
 * Up to 10 files (spec 9.5).
 */
attachments?: Array<AttachmentUpload>, 
/**
 * A reply of the bot, or a message it got, in its chat (spec 9.3).
 */
replyTo?: ChatItemId, };

/**
 * Newest first. Page back with `before` set to the oldest id received.
 */
export type MessagesListParams = { crewId?: CrewId, 
/**
 * Messages sent to or by this bot.
 */
botId?: BotId, 
/**
 * Only messages older than this one.
 */
before?: MessageId, 
/**
 * 1 to 200; 50 when absent.
 */
limit?: number, };

/**
 * Most recently updated first.
 */
export type DeliveriesListParams = { state?: DeliveryState, botId?: BotId, };

export type DeliveryIdParams = { deliveryId: DeliveryId, };

/**
 * Newest first.
 */
export type TasksListParams = { crewId?: CrewId, status?: TaskStatus, };

/**
 * Where a tool call the bot made stands.
 */
export type ToolStatus = "running" | "done" | "failed";

export type ApprovalStatus = "pending" | "allowed" | "denied" | "expired";

export type NoticeLevel = "info" | "warning" | "error";

/**
 * What a notice is about, so the app can say it in the owner's language.
 */
export type NoticeCode = "signed_out" | "usage_limit" | "turn_failed" | "model_unavailable" | "compacted" | "auto_compacted" | "compact_failed";

export type InboundItem = { message: Message, };

export type ReplyItem = { text: string, };

export type ToolItem = { toolUseId: string, name: string, 
/**
 * One line about what the call does, e.g. the command or the file.
 */
summary: string, 
/**
 * What the bot says a command is for, in its own words (spec 10.1);
 * absent when it said nothing, for other tools and for older items.
 */
explanation: string | null, 
/**
 * The call's input as JSON, cut at 4 KB.
 */
input: string, status: ToolStatus, 
/**
 * The start of what the tool returned, cut at 8 KB.
 */
output: string | null, 
/**
 * The full path of the file a `Write`/`Edit`/`NotebookEdit` call
 * changes; absent for other tools and for items stored before it existed.
 */
file: string | null, };

/**
 * What an allow rule covers, besides its tool.
 */
export type AllowKind = "command" | "site" | "file" | "tool";

/**
 * What "Allow always" would cover for one request: the tool and, for a
 * command, site or file, which one.
 */
export type AllowScope = { toolName: string, kind: AllowKind, 
/**
 * The command, the site or the file's path; empty for `tool`.
 */
value: string, };

/**
 * A request the bot no longer asks for: the daemon allows it alone.
 */
export type AllowRule = { id: RuleId, botId: BotId, scope: AllowScope, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, };

export type RulesListParams = { botId: BotId, };

export type RuleIdParams = { ruleId: RuleId, };

/**
 * A bot's rules after one was added or removed: the result of
 * `rules.delete` and the params of the `bot.rules` notification.
 */
export type BotRules = { botId: BotId, 
/**
 * Oldest first.
 */
rules: Array<AllowRule>, };

/**
 * What a grant reaches.
 */
export type DesktopScope = "app" | "desktop";

/**
 * What a grant lets the bot do: see, or see and act.
 */
export type DesktopLevel = "see" | "act";

/**
 * A grant of a bot on the owner's desktop.
 */
export type DesktopGrant = { id: DesktopGrantId, botId: BotId, scope: DesktopScope, 
/**
 * The executable, for an `app` grant.
 */
appPath: string | null, 
/**
 * The app's name for people ("Microsoft Excel"), for an `app` grant.
 */
appName: string | null, level: DesktopLevel, 
/**
 * The bot may use the owner's real mouse and keyboard (spec 24.7).
 */
realInput: boolean, 
/**
 * The bot may use it while the owner is away (spec 24.8).
 */
unattended: boolean, 
/**
 * When the owner accepted the risks screen (spec 24.10), Unix ms.
 */
acceptedRisksAt: number | null, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, };

export type DesktopGrantsParams = { botId: BotId, };

export type DesktopGrantIdParams = { grantId: DesktopGrantId, };

/**
 * `desktop.setOptions`: what the owner changes in a grant (spec 24.10).
 */
export type DesktopOptionsParams = { grantId: DesktopGrantId, 
/**
 * The bot may use the real mouse and keyboard there (spec 24.7).
 */
realInput?: boolean, 
/**
 * The bot may use the grant's reach while the owner is away (spec
 * 24.8); turning it on needs `acceptedRisks`.
 */
unattended?: boolean, 
/**
 * The owner checked "I understand the risks" on the risks screen
 * (spec 24.10).
 */
acceptedRisks?: boolean, };

/**
 * A bot's grants after one changed: the result of `desktop.revoke` and
 * the params of the `bot.desktop` notification.
 */
export type BotDesktop = { botId: BotId, 
/**
 * Oldest first.
 */
grants: Array<DesktopGrant>, };

/**
 * The window a bot is using on the owner's desktop.
 */
export type DesktopWindow = { id: number, title: string, 
/**
 * The app's name for people.
 */
app: string, };

/**
 * What a bot did in a window (spec 24.5), for its panel, which words it
 * in the owner's language.
 */
export type DesktopActionKind = "click" | "type" | "select" | "scroll" | "press";

export type DesktopAction = { kind: DesktopActionKind, 
/**
 * The control's name as the window reads it; empty when it has none.
 */
target: string, 
/**
 * The option chosen, for `select`.
 */
option: string | null, 
/**
 * Where in the window, as fractions of its width and height from its
 * top left corner, when the action has a point: for the bot's cursor
 * on its panel.
 */
x: number | null, y: number | null, };

/**
 * What a bot does on the owner's desktop, for its panel (spec 24.9): the
 * params of `desktop.changed`.
 */
export type DesktopState = { botId: BotId, 
/**
 * The window it read or acted in last.
 */
window: DesktopWindow | null, 
/**
 * What it did last; `null` after only reading.
 */
action: DesktopAction | null, 
/**
 * When it last read or acted, Unix ms.
 */
at: number | null, 
/**
 * The owner stopped it (spec 24.9): its desktop tools refuse until
 * they let it go on.
 */
stopped: boolean, };

/**
 * A picture of the window a bot is using, for whoever watches its panel.
 */
export type DesktopFrame = { botId: BotId, 
/**
 * JPEG, base64.
 */
data: string, width: number, height: number, };

/**
 * The result of `desktop.watch`: the bot's state and, when it uses a
 * window, its picture now.
 */
export type DesktopView = { state: DesktopState, frame: DesktopFrame | null, };

/**
 * `desktop.watch`, `desktop.stop` and `desktop.resume`.
 */
export type DesktopBotParams = { botId: BotId, };

/**
 * A bot used an app while the owner was away (spec 24.8): what the app
 * tells them when they are back, until they dismiss it. The result of
 * `desktop.awayUses` and the params of `desktop.away` are a list of these.
 */
export type DesktopAwayUse = { botId: BotId, 
/**
 * The app's name for people.
 */
app: string, 
/**
 * The first and the last use, Unix ms.
 */
from: number, until: number, 
/**
 * The newest item of the bot's chat at the first use, to open the chat
 * there.
 */
itemId: ChatItemId | null, };

/**
 * `desktop.grantWhole`: the owner gives the bot the whole desktop (spec
 * 24.10), never asked for in the chat.
 */
export type DesktopWholeParams = { botId: BotId, level: DesktopLevel, 
/**
 * The owner checked "I understand the risks"; without it, refused.
 */
acceptedRisks: boolean, };

/**
 * How Claude Code reaches the server.
 */
export type McpKind = "stdio" | "http";

/**
 * A registered server, without its secrets: the values of headers and
 * environment variables stay in `secrets\mcp` (spec 25.2), and only their
 * names come here.
 */
export type McpServer = { id: McpServerId, name: string, 
/**
 * The name Claude Code puts in the tools: `mcp__<slug>__<tool>`.
 */
slug: string, kind: McpKind, 
/**
 * `http` only.
 */
url: string | null, 
/**
 * `stdio` only.
 */
command: string | null, args: Array<string>, 
/**
 * Names of the headers (`http`); their values are secret.
 */
headerNames: Array<string>, 
/**
 * Names of the environment variables (`stdio`); their values are secret.
 */
envNames: Array<string>, 
/**
 * What the server is for, in the owner's words. Goes into the rules of
 * the bots that use it (spec 25.3).
 */
description: string, createdAt: number, };

/**
 * Whether Claude Code reached a server when the bot started (spec 25.5).
 */
export type McpState = "connected" | "pending" | "needs_auth" | "failed";

/**
 * What a bot's process reported about one of its servers.
 */
export type McpServerState = { serverId: McpServerId, state: McpState, 
/**
 * Why it failed, as Claude Code put it: for "Details", never the log.
 */
error: string | null, };

/**
 * The servers a bot uses, and how they stand since it started.
 */
export type BotMcp = { botId: BotId, serverIds: Array<McpServerId>, 
/**
 * Empty until the process says; only for servers it was started with.
 */
states: Array<McpServerState>, };

/**
 * Every server and who uses it: the result of `mcp.servers` and the params
 * of the `mcp.servers` notification.
 */
export type McpOverview = { 
/**
 * Oldest first.
 */
servers: Array<McpServer>, 
/**
 * Only the bots that use some server.
 */
bots: Array<BotMcp>, };

/**
 * Registers a server, or changes one when `server_id` is set. The header
 * and variable values are the secrets: when changing a server, an empty
 * value keeps the one already stored under that name.
 */
export type McpSaveParams = { serverId: McpServerId | null, name: string, kind: McpKind, url: string | null, command: string | null, args: Array<string>, headers: { [key in string]: string }, env: { [key in string]: string }, description: string, };

export type McpServerIdParams = { serverId: McpServerId, };

/**
 * Replaces the servers a bot uses.
 */
export type BotMcpSetParams = { botId: BotId, serverIds: Array<McpServerId>, };

/**
 * One lasting access: the whole crew, or one bot of it.
 */
export type CrewAccess = { id: CrewAccessId, 
/**
 * The bot that may reach.
 */
botId: BotId, crewId: CrewId, crewName: string, 
/**
 * One bot of the crew; `null` for the whole crew.
 */
targetBotId: BotId | null, targetName: string | null, 
/**
 * Talking with its bots: roster, messages and tasks.
 */
talk: boolean, 
/**
 * Reading their files; true whenever `edit` is.
 */
read: boolean, 
/**
 * Changing and adding files.
 */
edit: boolean, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, };

export type CrewAccessListParams = { botId: BotId, };

export type CrewAccessIdParams = { accessId: CrewAccessId, };

/**
 * The group a role is listed under.
 */
export type BotTemplateCategory = "code" | "design" | "content" | "research" | "business" | "product" | "marketing" | "learning" | "finance" | "people" | "security" | "health" | "games" | "legal";

/**
 * A role as the list shows it, in English. The app writes the name, role
 * and summary the owner reads in the owner's language (spec 26.2).
 */
export type BotTemplate = { 
/**
 * The sheet's file name: `code-reviewer`.
 */
id: string, category: BotTemplateCategory, name: string, role: string, summary: string, };

/**
 * A role with what a bot made from it starts with.
 */
export type BotTemplateFull = { id: string, category: BotTemplateCategory, name: string, role: string, summary: string, model: BotModel, effort: BotEffort, instructions: string, };

export type CatalogListParams = { category?: BotTemplateCategory, };

export type CatalogGetParams = { id: string, };

export type CatalogAddParams = { crewId: CrewId, templateId: string, 
/**
 * In the owner's language, as the app writes it.
 */
name: string, role: string, };

/**
 * How much a backup carries (spec 14.2).
 */
export type BackupScope = "full" | "light";

export type BackupCrew = { name: string, 
/**
 * The crew's bots, archived ones aside.
 */
bots: Array<string>, 
/**
 * A work folder the owner chose outside Botloft's folders: not in the
 * backup.
 */
workFolder: string | null, };

/**
 * What a backup holds, as its manifest says.
 */
export type BackupManifest = { 
/**
 * The archive's layout version.
 */
format: number, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * The Botloft version that made it.
 */
version: string, 
/**
 * Missing in a manifest from before the scope existed: `full`.
 */
scope: BackupScope, crews: Array<BackupCrew>, };

export type BackupExportParams = { passphrase: string, 
/**
 * `full` when missing.
 */
scope?: BackupScope, };

/**
 * A backup written and ready for the owner to save elsewhere.
 */
export type BackupExported = { path: string, 
/**
 * Bytes.
 */
size: number, manifest: BackupManifest, };

/**
 * `backup.stage`: a backup file the owner picked, and its passphrase.
 */
export type BackupStageParams = { path: string, passphrase: string, };

/**
 * `cloud.status`: where the owner stands with the account.
 */
export type CloudStatus = { 
/**
 * The server the app talks to; empty when none is set up.
 */
url: string, signedIn: boolean, email?: string, 
/**
 * Bytes the account's copies take, when the server answered.
 */
used?: number, 
/**
 * Bytes the account may keep, when the server answered.
 */
quota?: number, 
/**
 * A sign-in waits for the owner to open the link in the e-mail.
 */
pending: boolean, };

/**
 * `cloud.signin`: the e-mail the link goes to.
 */
export type CloudSigninParams = { email: string, 
/**
 * The app's language (`en`, `pt-BR`, `es`), for the e-mail.
 */
locale?: string, };

export type CloudSigninStarted = { 
/**
 * Seconds the link in the e-mail works.
 */
wait: number, };

/**
 * `cloud.upload`: the passphrase seals the copy, and never leaves here.
 */
export type CloudUploadParams = { passphrase: string, };

/**
 * A copy the account keeps.
 */
export type CloudCopy = { id: string, 
/**
 * Bytes.
 */
size: number, 
/**
 * Unix time in milliseconds.
 */
created: number, };

/**
 * `cloud.copies`, newest first.
 */
export type CloudCopies = { copies: Array<CloudCopy>, };

/**
 * `cloud.download` and `cloud.delete`: which copy.
 */
export type CloudCopyParams = { id: string, };

/**
 * A copy fetched, where the app goes on with `backup.stage`.
 */
export type CloudDownloaded = { path: string, };

/**
 * `cloud.signed_in`: the owner opened the link and this computer is in.
 */
export type CloudSignedIn = { email: string, };

/**
 * Which way the bytes of a [`CloudProgress`] go.
 */
export type CloudDirection = "upload" | "download";

/**
 * `cloud.progress`: how much of a copy went up or came down.
 */
export type CloudProgress = { direction: CloudDirection, sent: number, total: number, };

/**
 * How often the automatic backup looks for something new to send (spec 27.10).
 */
export type AutoBackupEvery = "daily" | "weekly";

/**
 * `autobackup.status` and the `autobackup.changed` notification.
 */
export type AutoBackupStatus = { 
/**
 * This computer can keep the passphrase safely (Windows today).
 */
available: boolean, enabled: boolean, every: AutoBackupEvery, 
/**
 * Unix time in milliseconds of the last copy it sent.
 */
lastOkAt?: number, 
/**
 * Unix time in milliseconds of the next look; absent when it is off.
 */
nextAt?: number, 
/**
 * Why the last try failed (a `reason` of 27.5, or `no_passphrase`).
 */
lastError?: string, };

/**
 * `autobackup.enable`: the passphrase is kept in the system's credential
 * store, and never leaves this computer.
 */
export type AutoBackupEnableParams = { passphrase: string, every: AutoBackupEvery, };

/**
 * `autobackup.set_every`
 */
export type AutoBackupEveryParams = { every: AutoBackupEvery, };

/**
 * Whether the computer's connection to the relay is up.
 */
export type MobileRelay = "off" | "connecting" | "connected";

/**
 * A phone the owner connected.
 */
export type MobilePhone = { id: string, name: string, 
/**
 * Unix time in milliseconds.
 */
pairedAt: number, 
/**
 * When the phone last sent anything, in Unix milliseconds.
 */
lastSeenAt?: number, online: boolean, };

/**
 * A phone that opened the QR code and waits for the owner to compare the
 * code and accept it.
 */
export type MobileJoined = { name: string, 
/**
 * Six digits, the same on the phone's screen.
 */
code: string, };

/**
 * A QR code on screen.
 */
export type MobilePairing = { pairId: string, 
/**
 * Unix time in milliseconds the code stops working.
 */
expiresAt: number, joined?: MobileJoined, };

/**
 * `mobile.status`, and the `mobile.changed` notification.
 */
export type MobileStatus = { relay: MobileRelay, phones: Array<MobilePhone>, pending?: MobilePairing, };

/**
 * `mobile.pair_start`: what the QR code carries.
 */
export type MobilePairStarted = { pairId: string, 
/**
 * The address the QR code holds, `#` and all.
 */
url: string, 
/**
 * Seconds the code works.
 */
expiresIn: number, };

/**
 * `mobile.pair_cancel`.
 */
export type MobilePairIdParams = { pairId: string, };

/**
 * `mobile.pair_confirm`: the owner compared the codes.
 */
export type MobilePairConfirmParams = { pairId: string, accept: boolean, };

/**
 * `mobile.revoke`.
 */
export type MobileRevokeParams = { phoneId: string, };

/**
 * The `mobile.pair_request` notification: a phone opened the code.
 */
export type MobilePairRequest = { pairId: string, name: string, code: string, };

/**
 * The bot that asks, as the phone shows it.
 */
export type CardBot = { name: string, color: string, };

/**
 * A request waiting for the owner, as the phone shows it (spec 28.5). It
 * carries what the owner needs to decide, and nothing else of the bot.
 */
export type ApprovalCard = { approvalId: ApprovalId, bot: CardBot, crew: string, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, toolName: string, summary: string, 
/**
 * What the bot says the command is for; the bot wrote it.
 */
explanation?: string, 
/**
 * The command, the plan or the request, whole unless `cut`.
 */
text: string, 
/**
 * `text` is not the whole request: the phone may only deny it.
 */
cut: boolean, 
/**
 * The request is of a kind that is answered at the computer: the phone
 * may only deny it.
 */
atComputer: boolean, };

/**
 * A question waiting for the owner, as the phone shows it.
 */
export type QuestionCard = { questionId: QuestionId, bot: CardBot, crew: string, createdAt: number, text: string, options: Array<string>, };

/**
 * A bot in the phone's list of conversations (spec 28.12).
 */
export type ChatLine = { botId: BotId, name: string, color: string, crew: string, state: BotState, 
/**
 * When the bot last finished a reply, in Unix milliseconds.
 */
lastReplyAt?: number, 
/**
 * The last thing in the chat, on one line.
 */
last?: Activity, 
/**
 * Up to when the owner read this chat on the computer, so the phone
 * does not mark as new what was read there.
 */
readAt?: number, };

/**
 * One thing in a conversation, as the phone shows it (spec 28.12): the
 * text, and never the output of a tool.
 */
export type PhoneItem = { "kind": "you", id: ChatItemId, at: number, text: string, cut: boolean, } | { "kind": "bot_message", id: ChatItemId, at: number, from: string, text: string, cut: boolean, } | { "kind": "reply", id: ChatItemId, at: number, text: string, cut: boolean, } | { "kind": "tool", id: ChatItemId, at: number, summary: string, } | { "kind": "approval", id: ChatItemId, at: number, approvalId: ApprovalId, summary: string, status: ApprovalStatus, } | { "kind": "question", id: ChatItemId, at: number, questionId: QuestionId, text: string, status: QuestionStatus, } | { "kind": "failed", id: ChatItemId, at: number, error?: string, } | { "kind": "notice", id: ChatItemId, at: number, level: NoticeLevel, text: string, };

/**
 * What the computer sends the phone, sealed (spec 28.3).
 */
export type ToPhone = { "t": "snapshot", approvals: Array<ApprovalCard>, questions: Array<QuestionCard>, } | { "t": "approval.open", card: ApprovalCard, } | { "t": "approval.closed", approvalId: ApprovalId, status: ApprovalStatus, } | { "t": "question.open", card: QuestionCard, } | { "t": "question.closed", questionId: QuestionId, status: QuestionStatus, } | { "t": "chats", bots: Array<ChatLine>, first: boolean, } | { "t": "history", req: number, botId: BotId, items: Array<PhoneItem>, more: boolean, done: boolean, } | { "t": "sent", clientId: string, ok: boolean, reason?: string, } | { "t": "item", botId: BotId, item: PhoneItem, } | { "t": "live", botId: BotId, text: string, } | { "t": "state", botId: BotId, state: BotState, } | { "t": "line", bot: ChatLine, } | { "t": "read", botId: BotId, upto: number, };

/**
 * What the phone sends the computer, sealed (spec 28.3).
 */
export type FromPhone = { "t": "sync" } | { "t": "approval.answer", approvalId: ApprovalId, allow: boolean, note?: string, } | { "t": "question.answer", questionId: QuestionId, answer: string, } | { "t": "question.dismiss", questionId: QuestionId, } | { "t": "chats" } | { "t": "history", req: number, botId: BotId, before?: ChatItemId, } | { "t": "send", clientId: string, botId: BotId, text: string, } | { "t": "watch", botId?: BotId, };

export type ApprovalItem = { approvalId: ApprovalId, toolName: string, summary: string, 
/**
 * What the bot says the command is for, as in `ToolItem`. The bot
 * wrote it: it goes before the command, never in its place. Kept only
 * here, not in the `Approval`.
 */
explanation: string | null, input: string, status: ApprovalStatus, 
/**
 * What the owner wrote with a denial.
 */
note: string | null, 
/**
 * What "Allow always" would cover (spec 10.1); `null` when the
 * request cannot be allowed for good. Kept only here, like the
 * explanation.
 */
always: AllowScope | null, };

/**
 * Tokens of one turn, as the `usage` of Claude Code's `result` event: the
 * sum of every request to the model in the turn.
 */
export type TokenUsage = { 
/**
 * New input the model read (`input_tokens`).
 */
input: number, 
/**
 * New input also written to the prompt cache (`cache_creation_input_tokens`).
 */
cacheWrite: number, 
/**
 * Of the cache write, the conversation from before written again because
 * the cache had expired: the daemon's estimate, 0 in older turns.
 */
reloaded: number, 
/**
 * Input read back from the prompt cache (`cache_read_input_tokens`):
 * mostly the conversation so far, and much cheaper than new input.
 */
cacheRead: number, 
/**
 * What the model wrote, thinking included (`output_tokens`).
 */
output: number, };

export type UsageTokensParams = { 
/**
 * Counts turns that ended at or after this Unix time in ms.
 */
since: number, };

/**
 * One bot's tokens since the time asked for.
 */
export type BotTokens = { botId: BotId, name: string, color: string, 
/**
 * The name of the bot's crew, so two bots with one name stay apart.
 */
crew: string, 
/**
 * The bot is archived.
 */
archived: boolean, 
/**
 * Turns that reported tokens.
 */
turns: number, tokens: TokenUsage, 
/**
 * About how much of the weekly plan the bot used in the period, 0 to
 * 1; `null` until Botloft has learned it (spec 8.7).
 */
planShare: number | null, };

export type QuestionStatus = "open" | "answered" | "dismissed";

export type Question = { id: QuestionId, crewId: CrewId, botId: BotId, 
/**
 * What the bot asks, markdown.
 */
text: string, 
/**
 * Ready answers the owner may pick; empty for a free answer only.
 */
options: Array<string>, status: QuestionStatus, 
/**
 * What the owner answered; `null` unless `answered`.
 */
answer: string | null, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds the owner answered or dismissed it.
 */
answeredAt: number | null, };

export type QuestionItem = { question: Question, };

/**
 * Newest first.
 */
export type QuestionsListParams = { 
/**
 * `open` when absent.
 */
status?: QuestionStatus, };

export type QuestionsAnswerParams = { questionId: QuestionId, answer: string, };

export type QuestionIdParams = { questionId: QuestionId, };

/** The emoji the owner can react with (spec 8.9). */
export const REACTIONS = ["👍", "❤️", "😂", "🎉", "🙏", "👀"] as const;

export type Reaction = { botId: BotId, 
/**
 * The bot's reply it is on.
 */
itemId: ChatItemId, 
/**
 * One of [`REACTIONS`].
 */
emoji: string, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * The owner's message that took it to the bot; `null` while it waits
 * for one.
 */
sentIn: MessageId | null, };

export type ReactionsListParams = { botId: BotId, };

/**
 * Puts the owner's reaction on a reply, or takes it off with `null`.
 */
export type ReactionsSetParams = { botId: BotId, itemId: ChatItemId, emoji: string | null, };

/**
 * A reaction was put, changed, sent or taken off (`reaction` is `null`).
 */
export type ReactionChanged = { botId: BotId, itemId: ChatItemId, reaction: Reaction | null, };

export type TurnItem = { durationMs: number, 
/**
 * Tokens the turn used (spec 8.7); `null` when Claude Code did not say
 * and on turns stored before it was kept.
 */
tokens: TokenUsage | null, 
/**
 * Why the turn failed, e.g. `rate_limit`; `null` when it worked.
 */
error: string | null, };

export type NoticeItem = { level: NoticeLevel, 
/**
 * Absent on notices stored before codes existed.
 */
code?: NoticeCode, 
/**
 * English text, or the detail for [`NoticeCode::TurnFailed`].
 */
text: string, };

/**
 * What a chat item holds, by `kind`.
 */
export type ChatBody = { "kind": "inbound" } & InboundItem | { "kind": "reply" } & ReplyItem | { "kind": "tool" } & ToolItem | { "kind": "approval" } & ApprovalItem | { "kind": "question" } & QuestionItem | { "kind": "turn" } & TurnItem | { "kind": "notice" } & NoticeItem;

/**
 * One entry of a bot's chat.
 */
export type ChatItem = { id: ChatItemId, botId: BotId, body: ChatBody, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds; changes when a tool ends or an approval is
 * answered.
 */
updatedAt: number, };

/**
 * Params of the `chat.item` notification: an item that is new or changed.
 */
export type ChatItemChanged = { item: ChatItem, 
/**
 * The bot's new conversation-list line; `null` when it did not change.
 */
activity: Activity | null, };

/** What a search snippet puts around each matched word (spec 8.8). */
export const SNIPPET_MARKS = { open: "\u0002", close: "\u0003" } as const;

/**
 * Newest first. Page back with `before` set to the oldest item received.
 */
export type ChatSearchParams = { 
/**
 * Words to find, as the owner typed them; the last one may be the
 * start of a word.
 */
query: string, 
/**
 * Only this bot's chat.
 */
botId?: BotId, 
/**
 * Only the chats of this crew's bots.
 */
crewId?: CrewId, before?: ChatItemId, 
/**
 * 1 to 100; 30 when absent.
 */
limit?: number, };

/**
 * A chat item with every searched word.
 */
export type SearchHit = { item: ChatItem, crewId: CrewId, 
/**
 * A few words around the match, on one line, with each matched word
 * between `\u0002` and `\u0003`.
 */
snippet: string, };

/**
 * A permission request (spec 10.1).
 */
export type Approval = { id: ApprovalId, botId: BotId, toolName: string, summary: string, input: string, status: ApprovalStatus, note: string | null, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds; `null` while pending.
 */
answeredAt: number | null, };

/**
 * Text the bot is writing right now, in order (spec 8.3).
 */
export type ChatDelta = { botId: BotId, text: string, };

/**
 * Newest first. Page back with `before` set to the oldest id received.
 */
export type ChatHistoryParams = { botId: BotId, before?: ChatItemId, 
/**
 * 1 to 200; 50 when absent.
 */
limit?: number, 
/**
 * Instead of a page: every item from this one to the newest, up to
 * 1,000 newest, to open the chat at a search result (spec 8.8).
 * Not with `before` or `limit`.
 */
until?: ChatItemId, };

export type ApprovalsAnswerParams = { approvalId: ApprovalId, allow: boolean, 
/**
 * Passed to the bot with a denial.
 */
note?: string, 
/**
 * A bot or routine suggestion as the owner changed it before allowing
 * it, in the JSON of the tool's input (spec 10.2, 20.12). Ignored for
 * other requests.
 */
input?: string, 
/**
 * With `allow`, the bot no longer asks for what the request's
 * `always` covers (spec 10.1). Ignored for a request without one.
 */
always?: boolean, };

/**
 * The daemon's part of the app's Settings.
 */
export type Settings = { 
/**
 * Botloft starts when the owner signs in to Windows (spec 14). Off,
 * the bots wait until the owner opens the app.
 */
startWithWindows: boolean, 
/**
 * The computer does not sleep while a bot works (spec 14).
 */
keepAwake: boolean, 
/**
 * How long a permission request waits for the owner before it is
 * denied (spec 10.1).
 */
approvalWaitMinutes: number, 
/**
 * The agent bots are made for when nothing says otherwise: new bots,
 * the chief of a new crew, the bots of a template (spec 30).
 */
defaultAgent: AgentKind, };

/**
 * The settings to change; the ones left out stay as they are.
 */
export type SettingsUpdateParams = { startWithWindows?: boolean, keepAwake?: boolean, 
/**
 * From 1 to [`APPROVAL_WAIT_MAX_MINUTES`].
 */
approvalWaitMinutes?: number, defaultAgent?: AgentKind, };

/**
 * When a routine runs (spec 20.2), kept as structure rather than cron text
 * so the app can show and edit it without jargon.
 */
export type Schedule = { "kind": "weekly", days: Array<number>, time: string, } | { "kind": "interval", minutes: number, } | { "kind": "cron", expr: string, } | { "kind": "signal", name: string, };

/**
 * What happens when a routine's time comes while its last run is still
 * waiting or working (spec 20.3).
 */
export type Overlap = "skip" | "queue";

/**
 * What happens with times that passed while the daemon was not running
 * (spec 20.4).
 */
export type Missed = "run_once" | "skip";

/**
 * Where a run is (spec 20.3).
 */
export type RunStatus = "queued" | "done" | "failed" | "skipped";

/**
 * Why a run was skipped.
 */
export type SkipReason = "overlap" | "bot_paused" | "missed" | "too_soon";

/**
 * A signal a bot sent (spec 20.13).
 */
export type RunSignal = { name: string, 
/**
 * The bot that sent it; `null` once that bot was deleted.
 */
fromBotId: BotId | null, 
/**
 * What the bot wrote with it.
 */
note: string | null, };

export type RoutineRun = { id: RoutineRunId, routineId: RoutineId, 
/**
 * The time it was for; the moment of the click for "run now".
 */
scheduledFor: number, status: RunStatus, reason: SkipReason | null, 
/**
 * For a `missed` skip: how many times passed.
 */
skippedCount: number, 
/**
 * The message it sent, unless skipped.
 */
messageId: MessageId | null, createdAt: number, finishedAt: number | null, 
/**
 * The signal that made it run, for a routine that waits for one.
 */
signal: RunSignal | null, };

export type Routine = { id: RoutineId, botId: BotId, name: string, 
/**
 * What the bot is asked to do, as the owner wrote it.
 */
prompt: string, schedule: Schedule, 
/**
 * IANA name, like `America/Sao_Paulo`.
 */
timezone: string, overlap: Overlap, missed: Missed, enabled: boolean, 
/**
 * Unix ms of the next scheduled time; `null` while disabled.
 */
nextRunAt: number | null, 
/**
 * The latest run, skipped ones included.
 */
lastRun: RoutineRun | null, createdAt: number, updatedAt: number, archivedAt: number | null, };

export type RoutinesListParams = { botId?: BotId, };

export type RoutinesCreateParams = { botId: BotId, name: string, prompt: string, schedule: Schedule, timezone: string, overlap?: Overlap, missed?: Missed, };

/**
 * Fields left out stay as they are.
 */
export type RoutinesUpdateParams = { routineId: RoutineId, name?: string, prompt?: string, schedule?: Schedule, timezone?: string, overlap?: Overlap, missed?: Missed, };

export type RoutinesSetEnabledParams = { routineId: RoutineId, enabled: boolean, };

export type RoutineIdParams = { routineId: RoutineId, };

export type RoutinesRunsParams = { routineId: RoutineId, before?: RoutineRunId, limit?: number, };

/**
 * Where a bot's browser is.
 */
export type BrowserStatus = "closed" | "starting" | "open" | "failed";

/**
 * Who uses a bot's browser right now.
 */
export type BrowserControl = "bot" | "owner";

/**
 * One of the browser's open tabs.
 */
export type BrowserTab = { 
/**
 * Names the tab in `browser.switchTab`; means nothing else.
 */
id: string, 
/**
 * Empty until the page has one.
 */
title: string, url: string, 
/**
 * The tab the bot's tools and the owner's hands act on.
 */
active: boolean, };

export type LessonStepKind = "open" | "click" | "type" | "press";

export type LessonStep = { kind: LessonStepKind, 
/**
 * The address for `open`, the element's name for `click` and `type`,
 * the key for `press`; at most 80 characters.
 */
label: string, 
/**
 * The element's role (`button`, `link`, `textbox`...), when it has one.
 */
role: string | null, 
/**
 * Typing in a password field: the bot asks the owner to type it.
 */
secret: boolean, };

export type BrowserState = { botId: BotId, status: BrowserStatus, 
/**
 * The active tab's address.
 */
url: string | null, title: string | null, 
/**
 * The active tab is loading a page.
 */
loading: boolean, 
/**
 * The open tabs, in the order they opened.
 */
tabs: Array<BrowserTab>, 
/**
 * Why it could not start, when `failed`.
 */
error: string | null, 
/**
 * Who uses it now (spec 21.10).
 */
control: BrowserControl, 
/**
 * Nobody uses it, so it rests: its pages stand still until the bot or
 * the owner needs them (spec 21.2).
 */
resting: boolean, 
/**
 * What the bot asked the owner to do in it, while it waits.
 */
ask: string | null, 
/**
 * The owner has it open in a window of its own, to sign in where a
 * site refuses a browser a program drives (spec 21.11). It is
 * `closed` meanwhile, and the bot's tools wait.
 */
window: boolean, 
/**
 * The steps of the lesson the owner is giving, while they teach the
 * bot a task (spec 21.13); `null` when nobody teaches.
 */
lesson: Array<LessonStep> | null, 
/**
 * Unix time in milliseconds.
 */
updatedAt: number, };

/**
 * One picture of the active tab, sent only to the connection watching it.
 */
export type BrowserFrame = { botId: BotId, 
/**
 * A JPEG, base64.
 */
data: string, 
/**
 * Size of the page it shows, in CSS pixels: the space of
 * `BrowserAction` points.
 */
width: number, height: number, };

export type BrowserActionKind = "open" | "click" | "type" | "select" | "press" | "scroll" | "back";

/**
 * Something the bot did in its browser, for the cursor in the app.
 */
export type BrowserAction = { botId: BotId, kind: BrowserActionKind, 
/**
 * Where on the page, in CSS pixels, when the action has a point.
 */
x: number | null, y: number | null, 
/**
 * The element's name, the key or the site; never the text typed.
 */
label: string | null, 
/**
 * Unix time in milliseconds.
 */
at: number, };

/**
 * What `browser.watch` answers: the state and the latest frame.
 */
export type BrowserView = { state: BrowserState, frame: BrowserFrame | null, };

export type BrowserWatchParams = { botId: BotId, };

/**
 * `browser.resize`: the room the app's panel has for the page, in the
 * app's pixels. The page takes its shape (spec 21.3).
 */
export type BrowserResizeParams = { botId: BotId, width: number, height: number, 
/**
 * The screen's pixels per pixel of the app, in percent (its
 * `devicePixelRatio` times 100). The daemon ignores it: the page is
 * always drawn in its own pixels, because a sharper page made clicks
 * land at the wrong point (spec 21.3, 19). Absent, 100.
 */
scale?: number, };

export type MouseAction = "move" | "down" | "up";

export type MouseButton = "none" | "left" | "middle" | "right";

/**
 * One thing the owner did on the page. Points are in CSS pixels of the
 * page, like `BrowserAction`.
 */
export type BrowserInput = { "kind": "mouse", action: MouseAction, x: number, y: number, button: MouseButton, 
/**
 * The buttons held: 1 left, 2 right, 4 middle.
 */
buttons: number, 
/**
 * 2 for a double click.
 */
clicks: number, modifiers: number, } | { "kind": "wheel", x: number, y: number, dx: number, dy: number, modifiers: number, } | { "kind": "key", key: string, code: string, modifiers: number, } | { "kind": "text", text: string, };

/**
 * `browser.take`, `browser.release`, `browser.reload`, `browser.newTab`
 * and `browser.window`.
 */
export type BrowserControlParams = { botId: BotId, };

export type BrowserInputParams = { botId: BotId, input: BrowserInput, };

/**
 * `browser.switchTab`: the tab that becomes the active one.
 */
export type BrowserTabParams = { botId: BotId, tabId: string, };

/**
 * `browser.open`: the address the owner typed for the active tab.
 */
export type BrowserOpenParams = { botId: BotId, url: string, };

/**
 * Starts or ends a lesson in the browser the connection has in its hands.
 */
export type BrowserTeachParams = { botId: BotId, on: boolean, };

/**
 * The device a screen is drawn for.
 */
export type ScreenDevice = "desktop" | "tablet" | "mobile";

/**
 * An HTML file the bot made, with where the app loads it.
 */
export type Screen = { 
/**
 * Absolute path.
 */
path: string, name: string, 
/**
 * As in `BotFile`.
 */
folder: string, 
/**
 * Unix time in milliseconds; the draft's time for a file not written yet.
 */
modifiedAt: number, 
/**
 * Where the app loads it (spec 22.2); changes when the file does.
 */
url: string, 
/**
 * What the file asks for with `<meta name="botloft-device">`.
 */
device: ScreenDevice | null, 
/**
 * The bot is writing it now.
 */
writing: boolean, };

export type ScreensListParams = { botId: BotId, };

/**
 * A new version of a screen the bot is writing (spec 22.3).
 */
export type ScreenDraft = { botId: BotId, 
/**
 * Absolute path of the file being written.
 */
path: string, 
/**
 * Where to load this version.
 */
url: string, 
/**
 * Counts up with each version of this draft.
 */
rev: number, 
/**
 * Bytes of the file written so far.
 */
bytes: number, 
/**
 * The write ended: the file on disk is the screen again.
 */
done: boolean, };

/** Params and result of every request method. */
export interface RpcMethods {
  "session.hello": { params: HelloParams; result: HelloResult };
  "session.setLocale": { params: LocaleParams; result: null };
  "system.status": { params: undefined; result: SystemStatus };
  "system.refresh": { params: undefined; result: SystemStatus };
  "settings.get": { params: undefined; result: Settings };
  "settings.update": { params: SettingsUpdateParams; result: Settings };
  "crews.list": { params: undefined; result: Array<Crew> };
  "crews.create": { params: CrewsCreateParams; result: Crew };
  "crews.rename": { params: CrewsRenameParams; result: Crew };
  "crews.setColor": { params: CrewsSetColorParams; result: Crew };
  "crews.setPaused": { params: CrewsSetPausedParams; result: Crew };
  "crews.setWorkFolder": { params: CrewsSetWorkFolderParams; result: Crew };
  "crews.setLead": { params: CrewsSetLeadParams; result: Crew };
  "crews.archive": { params: CrewIdParams; result: Crew };
  "crews.delete": { params: CrewsDeleteParams; result: CrewDeleted };
  "archive.list": { params: undefined; result: Archive };
  "bots.list": { params: BotsListParams; result: Array<Bot> };
  "bots.create": { params: BotsCreateParams; result: Bot };
  "bots.update": { params: BotsUpdateParams; result: Bot };
  "bots.setPaused": { params: BotsSetPausedParams; result: Bot };
  "bots.setPermissionMode": { params: BotsSetPermissionModeParams; result: Bot };
  "bots.setModel": { params: BotsSetModelParams; result: Bot };
  "bots.setAgentModel": { params: BotsSetAgentModelParams; result: Bot };
  "agents.models": { params: AgentsModelsParams; result: AgentModel[] };
  "bots.archive": { params: BotIdParams; result: Bot };
  "bots.delete": { params: BotsDeleteParams; result: BotDeleted };
  "bots.restart": { params: BotsRestartParams; result: Bot };
  "chat.history": { params: ChatHistoryParams; result: Array<ChatItem> };
  "chat.read": { params: BotIdParams; result: null };
  "approvals.answer": { params: ApprovalsAnswerParams; result: Approval };
  "messages.send": { params: MessagesSendParams; result: Message };
  "messages.list": { params: MessagesListParams; result: Array<Message> };
  "attachments.read": { params: AttachmentIdParams; result: AttachmentData };
  "files.list": { params: FilesListParams; result: Array<BotFile> };
  "files.read": { params: FilesReadParams; result: FileData };
  "deliveries.list": { params: DeliveriesListParams; result: Array<Delivery> };
  "deliveries.retry": { params: DeliveryIdParams; result: Delivery };
  "tasks.list": { params: TasksListParams; result: Array<Task> };
  "bots.setEffort": { params: BotsSetEffortParams; result: Bot };
  "bots.compact": { params: BotIdParams; result: Bot };
  "usage.tokens": { params: UsageTokensParams; result: Array<BotTokens> };
  "rules.list": { params: RulesListParams; result: Array<AllowRule> };
  "rules.delete": { params: RuleIdParams; result: BotRules };
  "desktop.grants": { params: DesktopGrantsParams; result: Array<DesktopGrant> };
  "desktop.revoke": { params: DesktopGrantIdParams; result: BotDesktop };
  "desktop.setOptions": { params: DesktopOptionsParams; result: BotDesktop };
  "desktop.grantWhole": { params: DesktopWholeParams; result: BotDesktop };
  "desktop.watch": { params: DesktopBotParams; result: DesktopView };
  "desktop.unwatch": { params: undefined; result: null };
  "desktop.stop": { params: DesktopBotParams; result: DesktopState };
  "desktop.resume": { params: DesktopBotParams; result: DesktopState };
  "desktop.awayUses": { params: undefined; result: Array<DesktopAwayUse> };
  "desktop.dismissAway": { params: undefined; result: null };
  "mcp.servers": { params: undefined; result: McpOverview };
  "mcp.save": { params: McpSaveParams; result: McpOverview };
  "mcp.delete": { params: McpServerIdParams; result: McpOverview };
  "bot.mcp.set": { params: BotMcpSetParams; result: BotMcp };
  "crewAccess.list": { params: CrewAccessListParams; result: Array<CrewAccess> };
  "crewAccess.revoke": { params: CrewAccessIdParams; result: Array<CrewAccess> };
  "catalog.list": { params: CatalogListParams; result: Array<BotTemplate> };
  "catalog.get": { params: CatalogGetParams; result: BotTemplateFull };
  "catalog.add": { params: CatalogAddParams; result: Bot };
  "backup.export": { params: BackupExportParams; result: BackupExported };
  "backup.stage": { params: BackupStageParams; result: BackupManifest };
  "backup.confirm": { params: undefined; result: null };
  "backup.cancel": { params: undefined; result: null };
  "cloud.status": { params: undefined; result: CloudStatus };
  "cloud.signin": { params: CloudSigninParams; result: CloudSigninStarted };
  "cloud.signin_cancel": { params: undefined; result: null };
  "cloud.signout": { params: undefined; result: null };
  "cloud.upload": { params: CloudUploadParams; result: CloudCopy };
  "cloud.copies": { params: undefined; result: CloudCopies };
  "cloud.download": { params: CloudCopyParams; result: CloudDownloaded };
  "cloud.delete": { params: CloudCopyParams; result: null };
  "cloud.delete_account": { params: undefined; result: null };
  "autobackup.status": { params: undefined; result: AutoBackupStatus };
  "autobackup.enable": { params: AutoBackupEnableParams; result: AutoBackupStatus };
  "autobackup.set_every": { params: AutoBackupEveryParams; result: AutoBackupStatus };
  "autobackup.disable": { params: undefined; result: AutoBackupStatus };
  "mobile.status": { params: undefined; result: MobileStatus };
  "mobile.pair_start": { params: undefined; result: MobilePairStarted };
  "mobile.pair_cancel": { params: MobilePairIdParams; result: null };
  "mobile.pair_confirm": { params: MobilePairConfirmParams; result: null };
  "mobile.revoke": { params: MobileRevokeParams; result: MobileStatus };
  "routines.list": { params: RoutinesListParams; result: Array<Routine> };
  "routines.create": { params: RoutinesCreateParams; result: Routine };
  "routines.update": { params: RoutinesUpdateParams; result: Routine };
  "routines.setEnabled": { params: RoutinesSetEnabledParams; result: Routine };
  "routines.runNow": { params: RoutineIdParams; result: RoutineRun };
  "routines.archive": { params: RoutineIdParams; result: Routine };
  "routines.runs": { params: RoutinesRunsParams; result: Array<RoutineRun> };
  "questions.list": { params: QuestionsListParams; result: Array<Question> };
  "questions.answer": { params: QuestionsAnswerParams; result: Question };
  "questions.dismiss": { params: QuestionIdParams; result: Question };
  "reactions.list": { params: ReactionsListParams; result: Array<Reaction> };
  "reactions.set": { params: ReactionsSetParams; result: Reaction | null };
  "chat.search": { params: ChatSearchParams; result: Array<SearchHit> };
  "browser.list": { params: undefined; result: Array<BrowserState> };
  "browser.watch": { params: BrowserWatchParams; result: BrowserView };
  "browser.unwatch": { params: undefined; result: null };
  "browser.resize": { params: BrowserResizeParams; result: null };
  "browser.take": { params: BrowserControlParams; result: BrowserState };
  "browser.release": { params: BrowserControlParams; result: BrowserState };
  "browser.window": { params: BrowserControlParams; result: BrowserState };
  "browser.start": { params: BrowserControlParams; result: BrowserState };
  "browser.teach": { params: BrowserTeachParams; result: Array<LessonStep> };
  "browser.input": { params: BrowserInputParams; result: null };
  "browser.reload": { params: BrowserControlParams; result: null };
  "browser.newTab": { params: BrowserControlParams; result: null };
  "browser.switchTab": { params: BrowserTabParams; result: null };
  "browser.open": { params: BrowserOpenParams; result: null };
  "screens.list": { params: ScreensListParams; result: Array<Screen> };
}

/** Params of every server notification. */
export interface RpcNotifications {
  "crew.changed": Crew;
  "bot.changed": Bot;
  "crew.deleted": CrewDeleted;
  "bot.deleted": BotDeleted;
  "folder.recycled": FolderRecycled;
  "bot.state": BotStateChanged;
  "chat.item": ChatItemChanged;
  "chat.delta": ChatDelta;
  "message.created": Message;
  "delivery.changed": Delivery;
  "task.changed": Task;
  "bot.context": BotContextChanged;
  "routine.changed": Routine;
  "routine.run": RoutineRun;
  "question.changed": Question;
  "reaction.changed": ReactionChanged;
  "bot.rules": BotRules;
  "bot.desktop": BotDesktop;
  "desktop.changed": DesktopState;
  "desktop.frame": DesktopFrame;
  "desktop.away": Array<DesktopAwayUse>;
  "mcp.servers": McpOverview;
  "bot.mcp": BotMcp;
  "cloud.signed_in": CloudSignedIn;
  "cloud.progress": CloudProgress;
  "cloud.signin_expired": null;
  "autobackup.changed": AutoBackupStatus;
  "mobile.changed": MobileStatus;
  "mobile.pair_request": MobilePairRequest;
  "browser.changed": BrowserState;
  "browser.action": BrowserAction;
  "browser.frame": BrowserFrame;
  "screen.draft": ScreenDraft;
}

export const RpcErrorCode = {
  parseError: -32700,
  invalidRequest: -32600,
  methodNotFound: -32601,
  invalidParams: -32602,
  internalError: -32603,
  notAuthenticated: -32001,
  notFound: -32002,
  conflict: -32003,
  validation: -32004,
  runtimeUnavailable: -32005,
} as const;
