// Generated by `cargo test -p botloft-core export_bindings`. Do not edit by hand.
// Source: crates/botloft-core/src/protocol.

export const PROTOCOL_VERSION = 1;

/**
 * Identifies a crew.
 */
export type CrewId = string;

/**
 * Identifies a bot.
 */
export type BotId = string;

/**
 * Identifies a message.
 */
export type MessageId = string;

/**
 * Identifies a delivery attempt record.
 */
export type DeliveryId = string;

/**
 * Identifies a task between bots.
 */
export type TaskId = string;

/**
 * A group of bots that can message each other and share a folder.
 */
export type Crew = { id: CrewId, name: string, 
/**
 * Folder name under the workspaces root. Set at creation, never changes.
 */
slug: string, paused: boolean, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds; `null` while the crew is active.
 */
archivedAt: number | null, };

/**
 * Lifecycle state of a bot (spec 7.1).
 */
export type BotState = "offline" | "launching" | "idle" | "busy" | "needs_approval" | "rate_limited" | "auth_error" | "backoff" | "archived";

/**
 * A persistent Claude Code session with a name, a role and instructions.
 */
export type Bot = { id: BotId, crewId: CrewId, name: string, 
/**
 * Address other bots use (`send_message(to: "<handle>")`). Derived from
 * the name and unique among the crew's active bots.
 */
handle: string, 
/**
 * Folder name inside the crew folder. Set at creation, never changes.
 */
slug: string, role: string, instructions: string, 
/**
 * Avatar color, `#RRGGBB`.
 */
color: string, paused: boolean, state: BotState, 
/**
 * Absolute path of the bot's workspace folder.
 */
workspace: string, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds; `null` while the bot is active.
 */
archivedAt: number | null, };

/**
 * Identifies the connecting app in `session.hello`.
 */
export type ClientInfo = { name: string, version: string, };

/**
 * First request of every connection.
 */
export type HelloParams = { 
/**
 * Owner token from `secrets\owner.token`.
 */
token: string, client: ClientInfo, protocol: number, };

export type HelloResult = { daemonVersion: string, protocol: number, };

export type SystemStatus = { daemonVersion: string, protocol: number, uptimeMs: number, 
/**
 * Version reported by `claude --version`; `null` until the runtime probe runs.
 */
claudeVersion: string | null, };

export type CrewsCreateParams = { name: string, };

export type CrewsRenameParams = { crewId: CrewId, name: string, };

export type CrewsSetPausedParams = { crewId: CrewId, paused: boolean, };

export type CrewIdParams = { crewId: CrewId, };

export type BotsListParams = { 
/**
 * Only bots of this crew; every active bot when absent.
 */
crewId?: CrewId, };

export type BotsCreateParams = { crewId: CrewId, name: string, role: string, instructions: string, 
/**
 * Avatar color `#RRGGBB`; the next palette color when absent.
 */
color?: string, };

/**
 * Fields left out stay unchanged.
 */
export type BotsUpdateParams = { botId: BotId, name?: string, role?: string, instructions?: string, color?: string, };

export type BotsSetPausedParams = { botId: BotId, paused: boolean, };

export type BotIdParams = { botId: BotId, };

/** Params and result of every request method. */
export interface RpcMethods {
  "session.hello": { params: HelloParams; result: HelloResult };
  "system.status": { params: undefined; result: SystemStatus };
  "crews.list": { params: undefined; result: Array<Crew> };
  "crews.create": { params: CrewsCreateParams; result: Crew };
  "crews.rename": { params: CrewsRenameParams; result: Crew };
  "crews.setPaused": { params: CrewsSetPausedParams; result: Crew };
  "crews.archive": { params: CrewIdParams; result: Crew };
  "bots.list": { params: BotsListParams; result: Array<Bot> };
  "bots.create": { params: BotsCreateParams; result: Bot };
  "bots.update": { params: BotsUpdateParams; result: Bot };
  "bots.setPaused": { params: BotsSetPausedParams; result: Bot };
  "bots.archive": { params: BotIdParams; result: Bot };
}

/** Params of every server notification. */
export interface RpcNotifications {
  "crew.changed": Crew;
  "bot.changed": Bot;
}

export const RpcErrorCode = {
  parseError: -32700,
  invalidRequest: -32600,
  methodNotFound: -32601,
  invalidParams: -32602,
  internalError: -32603,
  notAuthenticated: -32001,
  notFound: -32002,
  conflict: -32003,
  validation: -32004,
  runtimeUnavailable: -32005,
} as const;
