// Generated by `cargo test -p botloft-core export_bindings`. Do not edit by hand.
// Source: crates/botloft-core/src/protocol.

export const PROTOCOL_VERSION = 2;

/** Avatar colors the daemon assigns in order (spec 15.3). */
export const AVATAR_PALETTE = ["#FF7A59", "#5EC8FF", "#A48BFF", "#9BE564", "#FFC857", "#FF7EB6", "#3DD9C1", "#E8D5B0"] as const;

/** Longest values the daemon accepts, in characters (files, for attachments). */
export const FIELD_LIMITS = {
  name: 64,
  role: 200,
  instructions: 32000,
  message: 100000,
  attachments: 10,
} as const;

/**
 * Identifies a crew.
 */
export type CrewId = string;

/**
 * Identifies a bot.
 */
export type BotId = string;

/**
 * Identifies a message.
 */
export type MessageId = string;

/**
 * Identifies a delivery attempt record.
 */
export type DeliveryId = string;

/**
 * Identifies a task between bots.
 */
export type TaskId = string;

/**
 * Identifies an item of a bot's chat.
 */
export type ChatItemId = string;

/**
 * Identifies a permission request waiting for the owner.
 */
export type ApprovalId = string;

/**
 * Identifies a file the owner attached to a message.
 */
export type AttachmentId = string;

/**
 * A group of bots that can message each other and share a folder.
 */
export type Crew = { id: CrewId, name: string, 
/**
 * Folder name under the workspaces root. Set at creation, never changes.
 */
slug: string, paused: boolean, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds; `null` while the crew is active.
 */
archivedAt: number | null, };

/**
 * Lifecycle state of a bot (spec 7.1).
 */
export type BotState = "offline" | "launching" | "idle" | "busy" | "needs_approval" | "rate_limited" | "auth_error" | "backoff" | "archived";

/**
 * What the conversation-list line shows; the app words it.
 */
export type ActivityKind = "owner" | "message" | "reply" | "tool" | "approval" | "notice";

/**
 * The last thing in a bot's chat, for the conversation list.
 */
export type Activity = { kind: ActivityKind, 
/**
 * One line, at most 120 characters, without wording of its own.
 */
text: string, 
/**
 * Unix time in milliseconds.
 */
at: number, };

/**
 * A persistent Claude Code session with a name, a role and instructions.
 */
export type Bot = { id: BotId, crewId: CrewId, name: string, 
/**
 * Address other bots use (`send_message(to: "<handle>")`). Derived from
 * the name and unique among the crew's active bots.
 */
handle: string, 
/**
 * Folder name inside the crew folder. Set at creation, never changes.
 */
slug: string, role: string, instructions: string, 
/**
 * Avatar color, `#RRGGBB`.
 */
color: string, paused: boolean, state: BotState, 
/**
 * Current process generation; `null` if the bot has not started since
 * the daemon did. Changes on every (re)start.
 */
generation: number | null, 
/**
 * Absolute path of the bot's workspace folder.
 */
workspace: string, 
/**
 * The last item of the bot's chat, in one line; `null` for a new bot.
 */
lastActivity: Activity | null, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds; `null` while the bot is active.
 */
archivedAt: number | null, };

/**
 * Identifies the connecting app in `session.hello`.
 */
export type ClientInfo = { name: string, version: string, };

/**
 * First request of every connection.
 */
export type HelloParams = { 
/**
 * Owner token from `secrets\owner.token`.
 */
token: string, client: ClientInfo, protocol: number, };

export type HelloResult = { daemonVersion: string, protocol: number, };

/**
 * Deliveries still to go and those that gave up, for `system.status`.
 */
export type DeliveryBacklog = { 
/**
 * `pending` and `sending`.
 */
pending: number, dead: number, };

export type UsageWindow = { 
/**
 * `five_hour`, `seven_day`...
 */
name: string, 
/**
 * Share used, 0 to 1.
 */
utilization: number, 
/**
 * Unix time in milliseconds.
 */
resetsAt: number | null, };

/**
 * The account's usage, from Claude Code's `rate_limit_event` (spec 8.1).
 */
export type AccountUsage = { 
/**
 * As Claude Code says it: `allowed`, `allowed_warning`, `rejected`...
 */
status: string, 
/**
 * Unix time in milliseconds when the current limit resets.
 */
resetsAt: number | null, windows: Array<UsageWindow>, 
/**
 * Unix time in milliseconds.
 */
observedAt: number, };

/**
 * What `claude auth status` says about the account (spec 7.3).
 */
export type ClaudeAccount = { email: string | null, 
/**
 * As Claude Code says it: `max`, `pro`, `team`, `enterprise`...
 */
plan: string | null, organization: string | null, };

/**
 * The owner, as the app shows them in its account area (spec 15.1).
 */
export type OwnerAccount = { 
/**
 * The Windows account's display name, or the user name without one.
 */
name: string, 
/**
 * The Claude account Claude Code is signed in to; `null` when signed out
 * or not checked yet.
 */
claude: ClaudeAccount | null, };

export type SystemStatus = { daemonVersion: string, protocol: number, uptimeMs: number, 
/**
 * Version reported by `claude --version`; `null` until the runtime probe runs.
 */
claudeVersion: string | null, 
/**
 * Why bots cannot start (Claude Code missing or too old); `null` when fine.
 */
runtimeError: string | null, 
/**
 * The Claude Code executable the bots run; `null` until it is found.
 */
claudePath: string | null, 
/**
 * Whether Claude Code is signed in (`claude auth status`); `null` until checked.
 */
claudeSignedIn: boolean | null, 
/**
 * Who the owner is, for the account area of the app.
 */
account: OwnerAccount, deliveries: DeliveryBacklog, 
/**
 * The Claude account's usage as last reported; `null` before any turn.
 */
usage: AccountUsage | null, };

export type CrewsCreateParams = { name: string, };

export type CrewsRenameParams = { crewId: CrewId, name: string, };

export type CrewsSetPausedParams = { crewId: CrewId, paused: boolean, };

export type CrewIdParams = { crewId: CrewId, };

export type BotsListParams = { 
/**
 * Only bots of this crew; every active bot when absent.
 */
crewId?: CrewId, };

export type BotsCreateParams = { crewId: CrewId, name: string, role: string, instructions: string, 
/**
 * Avatar color `#RRGGBB`; the next palette color when absent.
 */
color?: string, };

/**
 * Fields left out stay unchanged.
 */
export type BotsUpdateParams = { botId: BotId, name?: string, role?: string, instructions?: string, color?: string, };

export type BotsSetPausedParams = { botId: BotId, paused: boolean, };

export type BotIdParams = { botId: BotId, };

export type BotsRestartParams = { botId: BotId, 
/**
 * Start a new conversation instead of resuming the last one.
 */
fresh?: boolean, };

/**
 * Params of the `bot.state` notification.
 */
export type BotStateChanged = { botId: BotId, state: BotState, generation: number | null, };

/**
 * Who wrote a message.
 */
export type SenderKind = "owner" | "bot" | "system";

/**
 * What a message is for.
 */
export type MessageKind = "note" | "task" | "result" | "system";

/**
 * Where a delivery is in the courier (spec 9.1).
 */
export type DeliveryState = "pending" | "sending" | "sent" | "dead";

export type TaskStatus = "open" | "done" | "failed" | "cancelled" | "expired";

/**
 * A file attached to a message, saved in the bot's folder.
 */
export type Attachment = { id: AttachmentId, 
/**
 * File name as saved, without folders.
 */
name: string, mediaType: string, 
/**
 * Bytes.
 */
size: number, 
/**
 * Path relative to the bot's workspace, with forward slashes.
 */
path: string, };

/**
 * A file the owner sends with `messages.send`.
 */
export type AttachmentUpload = { name: string, mediaType: string, 
/**
 * The file's bytes, base64.
 */
data: string, };

export type AttachmentIdParams = { attachmentId: AttachmentId, };

/**
 * A saved attachment's bytes, for the app to show (spec 9.5).
 */
export type AttachmentData = { mediaType: string, 
/**
 * The file's bytes, base64.
 */
data: string, };

/**
 * Text sent to a bot, by the owner, another bot or the daemon.
 */
export type Message = { id: MessageId, crewId: CrewId, fromKind: SenderKind, 
/**
 * Set when `fromKind` is `bot`.
 */
fromBotId: BotId | null, toBotId: BotId, kind: MessageKind, body: string, 
/**
 * The task this message asks for, answers or reports on.
 */
taskId: TaskId | null, 
/**
 * Files the owner attached (spec 9.5); empty for everything else.
 */
attachments: Array<Attachment>, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, };

/**
 * Getting one message into one bot's process.
 */
export type Delivery = { id: DeliveryId, messageId: MessageId, botId: BotId, state: DeliveryState, 
/**
 * Failed attempts so far. Waiting for the bot to be ready is not one.
 */
attempts: number, 
/**
 * Unix time in milliseconds of the next try while `pending`.
 */
nextAttemptAt: number, 
/**
 * Why the last attempt failed; never contains the message body.
 */
lastError: string | null, 
/**
 * Unix time in milliseconds the bot began the turn for this message.
 */
readAt: number | null, 
/**
 * Unix time in milliseconds.
 */
updatedAt: number, };

/**
 * Work one bot asked another to do (spec 9.4).
 */
export type Task = { id: TaskId, crewId: CrewId, requesterBotId: BotId, assigneeBotId: BotId, status: TaskStatus, 
/**
 * Unix time in milliseconds.
 */
deadlineAt: number, 
/**
 * Position in a chain of delegations: 1 for a task nobody else caused.
 */
hops: number, 
/**
 * First task of the chain this one belongs to; `null` for that first task.
 */
originTaskId: TaskId | null, result: string | null, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds.
 */
updatedAt: number, };

/**
 * The owner writes to a bot.
 */
export type MessagesSendParams = { botId: BotId, body: string, 
/**
 * Up to 10 files (spec 9.5).
 */
attachments?: Array<AttachmentUpload>, };

/**
 * Newest first. Page back with `before` set to the oldest id received.
 */
export type MessagesListParams = { crewId?: CrewId, 
/**
 * Messages sent to or by this bot.
 */
botId?: BotId, 
/**
 * Only messages older than this one.
 */
before?: MessageId, 
/**
 * 1 to 200; 50 when absent.
 */
limit?: number, };

/**
 * Most recently updated first.
 */
export type DeliveriesListParams = { state?: DeliveryState, botId?: BotId, };

export type DeliveryIdParams = { deliveryId: DeliveryId, };

/**
 * Newest first.
 */
export type TasksListParams = { crewId?: CrewId, status?: TaskStatus, };

/**
 * Where a tool call the bot made stands.
 */
export type ToolStatus = "running" | "done" | "failed";

export type ApprovalStatus = "pending" | "allowed" | "denied" | "expired";

export type NoticeLevel = "info" | "warning" | "error";

/**
 * What a notice is about, so the app can say it in the owner's language.
 */
export type NoticeCode = "signed_out" | "usage_limit" | "turn_failed";

export type InboundItem = { message: Message, };

export type ReplyItem = { text: string, };

export type ToolItem = { toolUseId: string, name: string, 
/**
 * One line about what the call does, e.g. the command or the file.
 */
summary: string, 
/**
 * The call's input as JSON, cut at 4 KB.
 */
input: string, status: ToolStatus, 
/**
 * The start of what the tool returned, cut at 8 KB.
 */
output: string | null, };

export type ApprovalItem = { approvalId: ApprovalId, toolName: string, summary: string, input: string, status: ApprovalStatus, 
/**
 * What the owner wrote with a denial.
 */
note: string | null, };

export type TurnItem = { durationMs: number, 
/**
 * As Claude Code reports it; `null` when it did not.
 */
costUsd: number | null, 
/**
 * Why the turn failed, e.g. `rate_limit`; `null` when it worked.
 */
error: string | null, };

export type NoticeItem = { level: NoticeLevel, 
/**
 * Absent on notices stored before codes existed.
 */
code?: NoticeCode, 
/**
 * English text, or the detail for [`NoticeCode::TurnFailed`].
 */
text: string, };

/**
 * What a chat item holds, by `kind`.
 */
export type ChatBody = { "kind": "inbound" } & InboundItem | { "kind": "reply" } & ReplyItem | { "kind": "tool" } & ToolItem | { "kind": "approval" } & ApprovalItem | { "kind": "turn" } & TurnItem | { "kind": "notice" } & NoticeItem;

/**
 * One entry of a bot's chat.
 */
export type ChatItem = { id: ChatItemId, botId: BotId, body: ChatBody, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds; changes when a tool ends or an approval is
 * answered.
 */
updatedAt: number, };

/**
 * Params of the `chat.item` notification: an item that is new or changed.
 */
export type ChatItemChanged = { item: ChatItem, 
/**
 * The bot's new conversation-list line; `null` when it did not change.
 */
activity: Activity | null, };

/**
 * A permission request (spec 10.1).
 */
export type Approval = { id: ApprovalId, botId: BotId, toolName: string, summary: string, input: string, status: ApprovalStatus, note: string | null, 
/**
 * Unix time in milliseconds.
 */
createdAt: number, 
/**
 * Unix time in milliseconds; `null` while pending.
 */
answeredAt: number | null, };

/**
 * Text the bot is writing right now, in order (spec 8.3).
 */
export type ChatDelta = { botId: BotId, text: string, };

/**
 * Newest first. Page back with `before` set to the oldest id received.
 */
export type ChatHistoryParams = { botId: BotId, before?: ChatItemId, 
/**
 * 1 to 200; 50 when absent.
 */
limit?: number, };

export type ApprovalsAnswerParams = { approvalId: ApprovalId, allow: boolean, 
/**
 * Passed to the bot with a denial.
 */
note?: string, };

/** Params and result of every request method. */
export interface RpcMethods {
  "session.hello": { params: HelloParams; result: HelloResult };
  "system.status": { params: undefined; result: SystemStatus };
  "system.refresh": { params: undefined; result: SystemStatus };
  "crews.list": { params: undefined; result: Array<Crew> };
  "crews.create": { params: CrewsCreateParams; result: Crew };
  "crews.rename": { params: CrewsRenameParams; result: Crew };
  "crews.setPaused": { params: CrewsSetPausedParams; result: Crew };
  "crews.archive": { params: CrewIdParams; result: Crew };
  "bots.list": { params: BotsListParams; result: Array<Bot> };
  "bots.create": { params: BotsCreateParams; result: Bot };
  "bots.update": { params: BotsUpdateParams; result: Bot };
  "bots.setPaused": { params: BotsSetPausedParams; result: Bot };
  "bots.archive": { params: BotIdParams; result: Bot };
  "bots.restart": { params: BotsRestartParams; result: Bot };
  "chat.history": { params: ChatHistoryParams; result: Array<ChatItem> };
  "approvals.answer": { params: ApprovalsAnswerParams; result: Approval };
  "messages.send": { params: MessagesSendParams; result: Message };
  "messages.list": { params: MessagesListParams; result: Array<Message> };
  "attachments.read": { params: AttachmentIdParams; result: AttachmentData };
  "deliveries.list": { params: DeliveriesListParams; result: Array<Delivery> };
  "deliveries.retry": { params: DeliveryIdParams; result: Delivery };
  "tasks.list": { params: TasksListParams; result: Array<Task> };
}

/** Params of every server notification. */
export interface RpcNotifications {
  "crew.changed": Crew;
  "bot.changed": Bot;
  "bot.state": BotStateChanged;
  "chat.item": ChatItemChanged;
  "chat.delta": ChatDelta;
  "message.created": Message;
  "delivery.changed": Delivery;
  "task.changed": Task;
}

export const RpcErrorCode = {
  parseError: -32700,
  invalidRequest: -32600,
  methodNotFound: -32601,
  invalidParams: -32602,
  internalError: -32603,
  notAuthenticated: -32001,
  notFound: -32002,
  conflict: -32003,
  validation: -32004,
  runtimeUnavailable: -32005,
} as const;
