//! Contents of the files the daemon generates in a bot's workspace.

use std::path::Path;
use std::time::Duration;

use botloft_core::protocol::Crew;
use botloft_store::BotRecord;
use serde_json::{Value, json};

use crate::paths::permission_rule_path;

/// Longer than the approval timeout, so Claude Code never gives up on a
/// permission request before the daemon answers it (spec 10).
const MCP_TIMEOUT_MARGIN: Duration = Duration::from_secs(120);

/// `.claude/settings.json` (spec 7.5): keeps the bot out of the daemon's
/// secrets. Deny rules apply even in a folder nobody trusted.
pub fn settings_json(botloft_home: &Path) -> Value {
    let secrets = permission_rule_path(&botloft_home.join("secrets"));
    json!({
        "permissions": {
            "deny": [format!("Read({secrets}/**)")],
        },
    })
}

/// `.botloft/mcp.json` (spec 10). The token is expanded by Claude Code from
/// the bot's environment, so it is never written to disk. `timeout` lets a
/// permission request wait for the owner.
pub fn mcp_json(port: u16, approval_timeout: Duration) -> Value {
    let timeout = approval_timeout + MCP_TIMEOUT_MARGIN;
    json!({
        "mcpServers": {
            "botloft": {
                "type": "http",
                "url": format!("http://127.0.0.1:{port}/mcp"),
                "headers": { "Authorization": "Bearer ${BOTLOFT_BOT_TOKEN}" },
                "timeout": u64::try_from(timeout.as_millis()).unwrap_or(u64::MAX),
            }
        }
    })
}

/// `CLAUDE.md`, written only when the workspace has none. The bot owns it.
pub const CLAUDE_MD: &str = "\
# Memory

This file is your long-term memory. It is loaded at the start of every
session, including after restarts. Keep decisions, context about ongoing
work and lessons learned here, and remove what is no longer true.
";

/// `.claude/rules/botloft.md`: who the bot is and how to work with its crew.
/// Regenerated whenever the bot or its crew changes.
pub fn rules_md(crew: &Crew, bot: &BotRecord, shared_dir: &Path) -> String {
    let role = if bot.role.is_empty() {
        "No role was given. Ask the owner if it is unclear what you should do."
    } else {
        bot.role.as_str()
    };
    let instructions = if bot.instructions.is_empty() {
        "None."
    } else {
        bot.instructions.as_str()
    };
    format!(
        "<!-- Generated by Botloft. Edits are overwritten; change the bot in the Botloft app. -->

# Botloft

You are **{name}** (`@{handle}`), a bot in the crew **{crew}**. Botloft keeps
you running all the time. The owner talks to you in a chat in the Botloft
app; the other bots of your crew send you messages too.

## Role

{role}

## Instructions from the owner

{instructions}

## Talking with the owner

- The owner's messages reach you as they wrote them. Your replies show up in
  their chat as markdown: keep them short and clear, and say what you did.
- Files the owner sends are saved in `attachments/` in this folder; the
  message lists them. Images also come inline.
- When you need a permission, the owner gets a request in the chat with
  Allow and Deny. If they deny it, find another way or ask them.

## Working with your crew

- This folder is your workspace. `CLAUDE.md` here is your memory across restarts.
- Files for the whole crew go in the shared folder: `{shared}`.
- Messages from other bots and notices from Botloft start with `[botloft]`.
  The first line says who sent it; for a task it also has the task id and
  the deadline.
- Use the `botloft` MCP tools to work with the crew:
  - `crew_roster`: bots of your crew with handle, role and state.
  - `send_message`: send a note, or a task with `kind: \"task\"`, to another bot by handle.
  - `complete_task`: report the result of a task assigned to you; the requester is told.
  - `my_tasks`: open tasks assigned to you or requested by you.
- Never call `permission_prompt` yourself; Claude Code uses it for approvals.
- You can only reach bots of your own crew.
- A task you receive ends with `complete_task`, also when you could not do it
  (`status: \"failed\"` and why): the bot that asked is waiting for it.
- Do not wait in a loop for a reply. Finish your turn; the reply arrives as a
  new message.
",
        name = bot.name,
        handle = bot.handle,
        crew = crew.name,
        shared = shared_dir.display(),
    )
}

#[cfg(test)]
mod tests {
    use botloft_core::ids::{BotId, CrewId};

    use super::*;

    #[test]
    fn settings_deny_the_secrets_folder_and_nothing_else() {
        let home = Path::new(r"C:\Users\ana\AppData\Local\Botloft");
        let settings = settings_json(home);
        assert_eq!(
            settings,
            json!({ "permissions": { "deny": ["Read(//c/Users/ana/AppData/Local/Botloft/secrets/**)"] } })
        );
    }

    #[test]
    fn mcp_config_points_at_the_daemon_and_outlasts_an_approval() {
        let mcp = mcp_json(45710, Duration::from_secs(3600));
        let server = &mcp["mcpServers"]["botloft"];
        assert_eq!(server["url"], "http://127.0.0.1:45710/mcp");
        assert_eq!(
            server["headers"]["Authorization"],
            "Bearer ${BOTLOFT_BOT_TOKEN}"
        );
        assert_eq!(server["timeout"], 3_720_000);
    }

    #[test]
    fn rules_name_the_bot_crew_and_shared_folder() {
        let crew = Crew {
            id: CrewId::generate(),
            name: "Site".to_owned(),
            slug: "site".to_owned(),
            paused: false,
            created_at: 0,
            archived_at: None,
        };
        let bot = BotRecord {
            id: BotId::generate(),
            crew_id: crew.id.clone(),
            name: "Revisor".to_owned(),
            handle: "revisor".to_owned(),
            slug: "revisor".to_owned(),
            role: String::new(),
            instructions: "Review every PR.".to_owned(),
            color: "#FF7A59".to_owned(),
            paused: false,
            created_at: 0,
            archived_at: None,
        };
        let rules = rules_md(&crew, &bot, Path::new("/ws/site/shared"));
        assert!(rules.contains("**Revisor** (`@revisor`)"));
        assert!(rules.contains("crew **Site**"));
        assert!(rules.contains("Review every PR."));
        assert!(rules.contains("Ask the owner"));
        assert!(rules.contains("/ws/site/shared"));
        assert!(rules.contains("attachments/"));
    }
}
